"""Generate backward Node classes from DifferentiabilityInfo."""
from __future__ import annotations

from .model import DifferentiabilityInfo


def gen_functions(infos: list[DifferentiabilityInfo]) -> str:
    """Generate the full functions.py source."""
    parts = [_HEADER]
    for info in infos:
        parts.append(_gen_one_node(info))
    return "\n".join(parts) + "\n"


_HEADER = '''\
"""Auto-generated backward Node classes — DO NOT EDIT.

Generated by tools/autograd/gen_functions.py from derivatives.yaml.
"""
from __future__ import annotations

import math as _math

from ..autograd.node import Node
from .._backends.autograd import (
    _grad_context,
    _strip_autograd_keys,
    _backward_dispatch_keyset,
    _scalar_tensor_like,
)
from .._dispatch.dispatcher import redispatch
from ..autograd.utils import reduce_grad


def _inverse_permutation(dims):
    inv = [0] * len(dims)
    for i, d in enumerate(dims):
        inv[d] = i
    return inv


# ---------------------------------------------------------------------------
# Activation backward helpers (called from generated formulas)
# ---------------------------------------------------------------------------

def _softsign_grad(grad, self_, keyset):
    one = _scalar_tensor_like(self_, 1.0)
    denom = redispatch("add", keyset, one, redispatch("abs", keyset, self_))
    denom_sq = redispatch("mul", keyset, denom, denom)
    return redispatch("div", keyset, grad, denom_sq)


def _silu_grad(grad, self_, keyset):
    sig = redispatch("sigmoid", keyset, self_)
    ones = self_._ones_like()
    one_minus_sig = redispatch("add", keyset, ones, redispatch("neg", keyset, sig))
    x_mul = redispatch("mul", keyset, self_, one_minus_sig)
    factor = redispatch("mul", keyset, sig, redispatch("add", keyset, ones, x_mul))
    return redispatch("mul", keyset, grad, factor)


def _gelu_grad(grad, self_, keyset):
    sqrt2 = _scalar_tensor_like(self_, _math.sqrt(2.0))
    x_over_sqrt2 = redispatch("div", keyset, self_, sqrt2)
    erf_val = redispatch("erf", keyset, x_over_sqrt2)
    ones = self_._ones_like()
    half = _scalar_tensor_like(self_, 0.5)
    cdf = redispatch("mul", keyset, half, redispatch("add", keyset, ones, erf_val))
    coeff = _scalar_tensor_like(self_, 1.0 / _math.sqrt(2.0 * _math.pi))
    x_sq = redispatch("mul", keyset, self_, self_)
    neg_half_x_sq = redispatch("mul", keyset, _scalar_tensor_like(self_, -0.5), x_sq)
    pdf = redispatch("mul", keyset, coeff, redispatch("exp", keyset, neg_half_x_sq))
    x_pdf = redispatch("mul", keyset, self_, pdf)
    factor = redispatch("add", keyset, cdf, x_pdf)
    return redispatch("mul", keyset, grad, factor)


def _mish_grad(grad, self_, keyset):
    ones = self_._ones_like()
    sp = redispatch("softplus", keyset, self_)
    tanh_sp = redispatch("tanh", keyset, sp)
    tanh_sp_sq = redispatch("mul", keyset, tanh_sp, tanh_sp)
    sech2 = redispatch("add", keyset, ones, redispatch("neg", keyset, tanh_sp_sq))
    sig = redispatch("sigmoid", keyset, self_)
    tail = redispatch("mul", keyset, self_, redispatch("mul", keyset, sech2, sig))
    factor = redispatch("add", keyset, tanh_sp, tail)
    return redispatch("mul", keyset, grad, factor)


def _leaky_relu_grad(grad, self_, negative_slope, keyset):
    pos_mask = redispatch("sign", keyset, redispatch("relu", keyset, self_))
    ones = self_._ones_like()
    nonpos_mask = redispatch("add", keyset, ones, redispatch("neg", keyset, pos_mask))
    slope = _scalar_tensor_like(self_, negative_slope)
    factor = redispatch("add", keyset, pos_mask, redispatch("mul", keyset, nonpos_mask, slope))
    return redispatch("mul", keyset, grad, factor)


def _elu_grad(grad, self_, alpha, keyset):
    pos_mask = redispatch("sign", keyset, redispatch("relu", keyset, self_))
    ones = self_._ones_like()
    nonpos_mask = redispatch("add", keyset, ones, redispatch("neg", keyset, pos_mask))
    alpha_t = _scalar_tensor_like(self_, float(alpha))
    exp_x = redispatch("exp", keyset, self_)
    neg_branch = redispatch("mul", keyset, alpha_t, exp_x)
    factor = redispatch("add", keyset, pos_mask, redispatch("mul", keyset, nonpos_mask, neg_branch))
    return redispatch("mul", keyset, grad, factor)


def _celu_grad(grad, self_, alpha, keyset):
    alpha_t = _scalar_tensor_like(self_, float(alpha))
    small_eps = _scalar_tensor_like(self_, 1e-7)
    ones = self_._ones_like()
    pos_mask = redispatch("sign", keyset, redispatch("relu", keyset,
        redispatch("add", keyset, self_, small_eps)))
    neg_mask = redispatch("add", keyset, ones, redispatch("neg", keyset, pos_mask))
    exp_x_alpha = redispatch("exp", keyset, redispatch("div", keyset, self_, alpha_t))
    deriv = redispatch("add", keyset, pos_mask, redispatch("mul", keyset, neg_mask, exp_x_alpha))
    return redispatch("mul", keyset, grad, deriv)


def _hardtanh_grad(grad, self_, min_val, max_val, keyset):
    min_t = _scalar_tensor_like(self_, float(min_val))
    max_t = _scalar_tensor_like(self_, float(max_val))
    ge_min = redispatch("ge", keyset, self_, min_t)
    le_max = redispatch("le", keyset, self_, max_t)
    mask = redispatch("mul", keyset,
        redispatch("where", keyset, ge_min, self_._ones_like(), _scalar_tensor_like(self_, 0.0)),
        redispatch("where", keyset, le_max, self_._ones_like(), _scalar_tensor_like(self_, 0.0)))
    return redispatch("mul", keyset, grad, mask)


def _hardswish_grad(grad, self_, keyset):
    three = _scalar_tensor_like(self_, 3.0)
    sixth = _scalar_tensor_like(self_, 1.0 / 6.0)
    two = _scalar_tensor_like(self_, 2.0)
    ones = self_._ones_like()
    zero = _scalar_tensor_like(self_, 0.0)
    gt_neg3 = redispatch("gt", keyset, self_, redispatch("neg", keyset, three))
    lt_3 = redispatch("lt", keyset, self_, three)
    inner_mask = redispatch("mul", keyset,
        redispatch("where", keyset, gt_neg3, ones, zero),
        redispatch("where", keyset, lt_3, ones, zero))
    ge_3_mask = redispatch("where", keyset, redispatch("ge", keyset, self_, three), ones, zero)
    two_x_plus_3 = redispatch("add", keyset, redispatch("mul", keyset, two, self_), three)
    inner_grad = redispatch("mul", keyset, two_x_plus_3, sixth)
    dout = redispatch("add", keyset,
        redispatch("mul", keyset, inner_grad, inner_mask), ge_3_mask)
    return redispatch("mul", keyset, grad, dout)


def _hardsigmoid_grad(grad, self_, keyset):
    three = _scalar_tensor_like(self_, 3.0)
    sixth = _scalar_tensor_like(self_, 1.0 / 6.0)
    ones = self_._ones_like()
    zero = _scalar_tensor_like(self_, 0.0)
    gt_neg3 = redispatch("gt", keyset, self_, redispatch("neg", keyset, three))
    lt_3 = redispatch("lt", keyset, self_, three)
    inner_mask = redispatch("mul", keyset,
        redispatch("where", keyset, gt_neg3, ones, zero),
        redispatch("where", keyset, lt_3, ones, zero))
    return redispatch("mul", keyset, grad, redispatch("mul", keyset, inner_mask, sixth))


def _selu_grad(grad, self_, keyset):
    SCALE = 1.0507009873554804934193349852946
    ALPHA = 1.6732631921893986195596513061800
    scale_t = _scalar_tensor_like(self_, SCALE)
    alpha_scale_t = _scalar_tensor_like(self_, SCALE * ALPHA)
    small_eps = _scalar_tensor_like(self_, 1e-7)
    ones = self_._ones_like()
    pos_mask = redispatch("sign", keyset, redispatch("relu", keyset,
        redispatch("add", keyset, self_, small_eps)))
    neg_mask = redispatch("add", keyset, ones, redispatch("neg", keyset, pos_mask))
    exp_x = redispatch("exp", keyset, self_)
    neg_deriv = redispatch("mul", keyset, alpha_scale_t, exp_x)
    deriv = redispatch("add", keyset,
        redispatch("mul", keyset, pos_mask, scale_t),
        redispatch("mul", keyset, neg_mask, neg_deriv))
    return redispatch("mul", keyset, grad, deriv)


def _softmax_grad(grad, self_, dim, keyset):
    s = redispatch("softmax", keyset, self_, dim)
    gs = redispatch("mul", keyset, grad, s)
    gs_sum = redispatch("sum", keyset, gs, dim=dim, keepdim=True)
    return redispatch("mul", keyset, s, redispatch("add", keyset, grad,
        redispatch("neg", keyset, gs_sum)))


def _log_softmax_grad(grad, self_, dim, keyset):
    log_s = redispatch("log_softmax", keyset, self_, dim)
    s = redispatch("exp", keyset, log_s)
    grad_sum = redispatch("sum", keyset, grad, dim=dim, keepdim=True)
    return redispatch("add", keyset, grad,
        redispatch("neg", keyset, redispatch("mul", keyset, s, grad_sum)))


def _prelu_grad_input(grad, self_, weight, keyset):
    pos_mask = redispatch("sign", keyset, redispatch("relu", keyset, self_))
    ones = self_._ones_like()
    nonpos_mask = redispatch("add", keyset, ones, redispatch("neg", keyset, pos_mask))
    factor = redispatch("add", keyset, pos_mask, redispatch("mul", keyset, nonpos_mask, weight))
    return redispatch("mul", keyset, grad, factor)


def _prelu_grad_weight(grad, self_, weight, keyset):
    pos_mask = redispatch("sign", keyset, redispatch("relu", keyset, self_))
    ones = self_._ones_like()
    nonpos_mask = redispatch("add", keyset, ones, redispatch("neg", keyset, pos_mask))
    w_input = redispatch("mul", keyset, nonpos_mask, self_)
    return redispatch("mul", keyset, grad, w_input)


# ---------------------------------------------------------------------------
# Norm backward helpers (called from generated formulas)
# ---------------------------------------------------------------------------

def _norm_stats(x, axes, eps, keyset):
    """Shared: compute mean, diff, inv_std, x_hat for norm backward."""
    mean = redispatch("mean", keyset, x, dim=axes, keepdim=True)
    diff = redispatch("add", keyset, x, redispatch("neg", keyset, mean))
    var = redispatch("mean", keyset, redispatch("mul", keyset, diff, diff), dim=axes, keepdim=True)
    eps_t = _scalar_tensor_like(x, eps)
    inv_std = redispatch("rsqrt", keyset, redispatch("add", keyset, var, eps_t))
    x_hat = redispatch("mul", keyset, diff, inv_std)
    return inv_std, x_hat


def _norm_grad_core(dl_dxhat, x_hat, inv_std, axes, n, keyset):
    """Shared: compute grad_input from dl_dxhat, x_hat, inv_std."""
    n_t = _scalar_tensor_like(x_hat, float(n))
    mean_dl = redispatch("div", keyset,
        redispatch("sum", keyset, dl_dxhat, dim=axes, keepdim=True), n_t)
    mean_dl_xhat = redispatch("div", keyset,
        redispatch("sum", keyset, redispatch("mul", keyset, dl_dxhat, x_hat),
                   dim=axes, keepdim=True), n_t)
    return redispatch("mul", keyset, inv_std,
        redispatch("add", keyset,
            redispatch("add", keyset, dl_dxhat, redispatch("neg", keyset, mean_dl)),
            redispatch("neg", keyset, redispatch("mul", keyset, x_hat, mean_dl_xhat))))


def _layer_norm_grad_input(grad, input_, normalized_shape, weight, eps, keyset):
    norm_shape = tuple(normalized_shape)
    ndim = len(input_.shape)
    n_norm = len(norm_shape)
    axes = tuple(range(ndim - n_norm, ndim))
    inv_std, x_hat = _norm_stats(input_, axes, eps, keyset)
    dl_dxhat = redispatch("mul", keyset, grad, weight) if weight is not None else grad
    n = 1
    for d in axes:
        n *= input_.shape[d]
    return _norm_grad_core(dl_dxhat, x_hat, inv_std, axes, n, keyset)


def _layer_norm_backward_all(grad, input_, normalized_shape, weight, bias, eps, keyset):
    norm_shape = tuple(normalized_shape)
    ndim = len(input_.shape)
    n_norm = len(norm_shape)
    axes = tuple(range(ndim - n_norm, ndim))
    inv_std, x_hat = _norm_stats(input_, axes, eps, keyset)
    dl_dxhat = redispatch("mul", keyset, grad, weight) if weight is not None else grad
    n = 1
    for d in axes:
        n *= input_.shape[d]
    grad_input = _norm_grad_core(dl_dxhat, x_hat, inv_std, axes, n, keyset)
    grad_weight = None
    if weight is not None:
        batch_dims = tuple(range(ndim - n_norm))
        grad_weight = redispatch("sum", keyset, redispatch("mul", keyset, grad, x_hat), dim=batch_dims)
    grad_bias = None
    if bias is not None:
        batch_dims = tuple(range(ndim - n_norm))
        grad_bias = redispatch("sum", keyset, grad, dim=batch_dims)
    return grad_input, grad_weight, grad_bias


def _batch_norm_grad_input(grad, input_, weight, eps, keyset):
    ndim = len(input_.shape)
    axes = (0,) + tuple(range(2, ndim))
    shape_for_stats = [1, input_.shape[1]] + [1] * (ndim - 2)
    inv_std, x_hat = _norm_stats(input_, axes, eps, keyset)
    if weight is not None:
        dl_dxhat = redispatch("mul", keyset, grad, weight.reshape(shape_for_stats))
    else:
        dl_dxhat = grad
    n = 1
    for ax in axes:
        n *= input_.shape[ax]
    return _norm_grad_core(dl_dxhat, x_hat, inv_std, axes, n, keyset)


def _group_norm_grad_input(grad, input_, num_groups, weight, eps, keyset):
    N = input_.shape[0]
    C = input_.shape[1]
    spatial = input_.shape[2:]
    channels_per_group = C // num_groups
    group_size = channels_per_group
    for s in spatial:
        group_size *= s
    reshaped = redispatch("reshape", keyset, input_,
                          (N, num_groups, channels_per_group, *spatial))
    axes = tuple(range(2, len(reshaped.shape)))
    inv_std, x_hat = _norm_stats(reshaped, axes, eps, keyset)
    grad_reshaped = redispatch("reshape", keyset, grad,
                               (N, num_groups, channels_per_group, *spatial))
    if weight is not None:
        w_shape = [1, num_groups, channels_per_group] + [1] * len(spatial)
        w_reshaped = redispatch("reshape", keyset, weight, tuple(w_shape))
        dl_dxhat = redispatch("mul", keyset, grad_reshaped, w_reshaped)
    else:
        dl_dxhat = grad_reshaped
    grad_out = _norm_grad_core(dl_dxhat, x_hat, inv_std, axes, group_size, keyset)
    return redispatch("reshape", keyset, grad_out, input_.shape)


def _rms_norm_grad_input(grad, input_, normalized_shape, weight, eps, keyset):
    norm_shape = tuple(normalized_shape)
    ndim = len(input_.shape)
    n_norm = len(norm_shape)
    axes = tuple(range(ndim - n_norm, ndim))
    x_sq = redispatch("mul", keyset, input_, input_)
    variance = redispatch("mean", keyset, x_sq, dim=axes, keepdim=True)
    eps_t = _scalar_tensor_like(input_, eps)
    rms = redispatch("sqrt", keyset, redispatch("add", keyset, variance, eps_t))
    x_hat = redispatch("div", keyset, input_, rms)
    dl_dxhat = redispatch("mul", keyset, grad, weight) if weight is not None else grad
    n = 1
    for d in axes:
        n *= input_.shape[d]
    n_t = _scalar_tensor_like(input_, float(n))
    dot = redispatch("sum", keyset,
        redispatch("mul", keyset, dl_dxhat, x_hat), dim=axes, keepdim=True)
    return redispatch("div", keyset,
        redispatch("add", keyset, dl_dxhat,
            redispatch("neg", keyset, redispatch("mul", keyset, x_hat,
                redispatch("div", keyset, dot, n_t)))),
        rms)


# ---------------------------------------------------------------------------
# Conv backward helpers (Phase 2)
# ---------------------------------------------------------------------------

class _ConvGradCache:
    """Cache conv backward results to avoid recomputation across grad formulas."""
    _cache = {}

    @classmethod
    def get(cls, key, compute_fn):
        if key not in cls._cache:
            cls._cache[key] = compute_fn()
        return cls._cache[key]

    @classmethod
    def clear(cls):
        cls._cache.clear()


def _conv_backward_all(grad, input_, weight, bias, stride, padding, dilation, groups, name, keyset):
    """Compute all conv gradients, returning (grad_input, grad_weight, grad_bias).

    Delegates to the existing _conv_backward implementation.
    Always returns a 3-tuple (grad_bias is None when bias is None).
    """
    from .._backends.autograd import _conv_backward
    args = (stride, padding, dilation, groups)
    result = _conv_backward(name, grad, input_, weight, bias,
                            input_, weight, bias, keyset, args, {})
    if len(result) == 2:
        return result[0], result[1], None
    return result


# ---------------------------------------------------------------------------
# Pool backward helpers (Phase 2)
# ---------------------------------------------------------------------------

def _max_pool1d_backward_helper(grad, self_, result, kernel_size, stride, padding, dilation, ceil_mode, keyset):
    from .._backends.autograd import _max_pool1d_backward
    args = (kernel_size, stride, padding, dilation, ceil_mode)
    return _max_pool1d_backward(grad, self_, self_, result, keyset, args, {})[0]


def _max_pool2d_backward_helper(grad, self_, result, kernel_size, stride, padding, dilation, ceil_mode, keyset):
    from .._backends.autograd import _max_pool2d_backward
    args = (kernel_size, stride, padding, dilation, ceil_mode)
    return _max_pool2d_backward(grad, self_, self_, result, keyset, args, {})[0]


def _max_pool3d_backward_helper(grad, self_, result, kernel_size, stride, padding, dilation, ceil_mode, keyset):
    from .._backends.autograd import _max_pool3d_backward
    args = (kernel_size, stride, padding, dilation, ceil_mode)
    return _max_pool3d_backward(grad, self_, self_, result, keyset, args, {})[0]


def _avg_pool1d_backward_helper(grad, self_, kernel_size, stride, padding, ceil_mode, count_include_pad, keyset):
    from .._backends.autograd import _avg_pool1d_backward
    args = (kernel_size, stride, padding, ceil_mode, count_include_pad)
    return _avg_pool1d_backward(grad, self_, self_, None, keyset, args, {})[0]


def _avg_pool2d_backward_helper(grad, self_, kernel_size, stride, padding, ceil_mode, count_include_pad, keyset):
    from .._backends.autograd import _avg_pool2d_backward
    args = (kernel_size, stride, padding, ceil_mode, count_include_pad)
    return _avg_pool2d_backward(grad, self_, self_, None, keyset, args, {})[0]


def _avg_pool3d_backward_helper(grad, self_, kernel_size, stride, padding, ceil_mode, count_include_pad, keyset):
    from .._backends.autograd import _avg_pool3d_backward
    args = (kernel_size, stride, padding, ceil_mode, count_include_pad)
    return _avg_pool3d_backward(grad, self_, self_, None, keyset, args, {})[0]


def _adaptive_avg_pool1d_backward_helper(grad, self_, output_size, keyset):
    from .._backends.autograd import _adaptive_avg_pool1d_backward
    args = (output_size,)
    return _adaptive_avg_pool1d_backward(grad, self_, self_, None, keyset, args, {})[0]


def _adaptive_avg_pool2d_backward_helper(grad, self_, output_size, keyset):
    from .._backends.autograd import _adaptive_avg_pool2d_backward
    args = (output_size,)
    return _adaptive_avg_pool2d_backward(grad, self_, self_, None, keyset, args, {})[0]


def _adaptive_avg_pool3d_backward_helper(grad, self_, output_size, keyset):
    from .._backends.autograd import _adaptive_avg_pool3d_backward
    args = (output_size,)
    return _adaptive_avg_pool3d_backward(grad, self_, self_, None, keyset, args, {})[0]


def _adaptive_max_pool1d_backward_helper(grad, self_, result, output_size, keyset):
    from .._backends.autograd import _adaptive_max_pool1d_backward
    args = (output_size,)
    return _adaptive_max_pool1d_backward(grad, self_, self_, result, keyset, args, {})[0]


def _adaptive_max_pool2d_backward_helper(grad, self_, result, output_size, keyset):
    from .._backends.autograd import _adaptive_max_pool2d_backward
    args = (output_size,)
    return _adaptive_max_pool2d_backward(grad, self_, self_, result, keyset, args, {})[0]


# ---------------------------------------------------------------------------
# Upsample backward helpers (Phase 2)
# ---------------------------------------------------------------------------

def _upsample_nearest1d_backward_helper(grad, self_, output_size, keyset):
    from .._backends.autograd import _upsample_nearest1d_backward
    args = (output_size,)
    return _upsample_nearest1d_backward(grad, self_, self_, None, keyset, args, {})[0]


def _upsample_nearest2d_backward_helper(grad, self_, output_size, keyset):
    from .._backends.autograd import _upsample_nearest2d_backward
    args = (output_size,)
    return _upsample_nearest2d_backward(grad, self_, self_, None, keyset, args, {})[0]


def _upsample_bilinear2d_backward_helper(grad, self_, output_size, align_corners, keyset):
    from .._backends.autograd import _upsample_bilinear2d_backward
    args = (output_size, align_corners)
    return _upsample_bilinear2d_backward(grad, self_, self_, None, keyset, args, {})[0]


def _upsample_linear1d_backward_helper(grad, self_, output_size, align_corners, keyset):
    from .._backends.autograd import _upsample_linear1d_backward
    args = (output_size, align_corners)
    return _upsample_linear1d_backward(grad, self_, self_, None, keyset, args, {})[0]


def _upsample_bicubic2d_backward_helper(grad, self_, output_size, align_corners, keyset):
    from .._backends.autograd import _upsample_bicubic2d_backward
    args = (output_size, align_corners)
    return _upsample_bicubic2d_backward(grad, self_, self_, None, keyset, args, {})[0]


# ---------------------------------------------------------------------------
# Binary backward helpers (Batch 2)
# ---------------------------------------------------------------------------

def _add_backward_all(grad, self_, other, keyset):
    grad_self = reduce_grad(grad, self_.shape) if hasattr(self_, 'shape') else None
    grad_other = reduce_grad(grad, other.shape) if hasattr(other, 'shape') else None
    return grad_self, grad_other


def _sub_backward_all(grad, self_, other, keyset):
    grad_self = reduce_grad(grad, self_.shape) if hasattr(self_, 'shape') else None
    grad_other = None
    if hasattr(other, 'shape'):
        grad_other = reduce_grad(redispatch("neg", keyset, grad), other.shape)
    return grad_self, grad_other


def _mul_backward_all(grad, self_, other, keyset):
    if hasattr(other, 'shape'):
        g = redispatch("mul", keyset, grad, other)
        grad_self = reduce_grad(g, self_.shape)
    else:
        g = redispatch("mul", keyset, grad, _scalar_tensor_like(self_, float(other)))
        grad_self = reduce_grad(g, self_.shape)
    if hasattr(other, 'shape'):
        g = redispatch("mul", keyset, grad, self_)
        grad_other = reduce_grad(g, other.shape)
    else:
        grad_other = None
    return grad_self, grad_other


def _div_backward_all(grad, self_, other, keyset):
    if hasattr(other, 'shape'):
        grad_self = reduce_grad(redispatch("div", keyset, grad, other), self_.shape)
        other_sq = redispatch("mul", keyset, other, other)
        g = redispatch("neg", keyset, redispatch("div", keyset, redispatch("mul", keyset, grad, self_), other_sq))
        grad_other = reduce_grad(g, other.shape)
    else:
        # other is a scalar
        grad_self = reduce_grad(redispatch("div", keyset, grad, _scalar_tensor_like(self_, float(other))), self_.shape)
        grad_other = None
    return grad_self, grad_other


def _pow_backward_all(grad, self_, other, keyset):
    from .._backends.autograd import _pow_backward
    return _pow_backward(grad, self_, other, self_, other, keyset)


def _maximum_backward_all(grad, self_, other, keyset):
    from .._backends.autograd import _maximum_backward
    return _maximum_backward(grad, self_, other, self_, other, keyset)


def _minimum_backward_all(grad, self_, other, keyset):
    from .._backends.autograd import _minimum_backward
    return _minimum_backward(grad, self_, other, self_, other, keyset)


def _fmin_backward_all(grad, self_, other, keyset):
    from .._backends.autograd import _fmin_backward
    return _fmin_backward(grad, self_, other, self_, other, keyset)


def _fmax_backward_all(grad, self_, other, keyset):
    from .._backends.autograd import _fmax_backward
    return _fmax_backward(grad, self_, other, self_, other, keyset)


def _hypot_backward_all(grad, self_, other, keyset):
    from .._backends.autograd import _hypot_backward
    return _hypot_backward(grad, self_, other, self_, other, keyset)


def _logaddexp_backward_all(grad, self_, other, keyset):
    from .._backends.autograd import _logaddexp_backward
    return _logaddexp_backward(grad, self_, other, self_, other, keyset)


def _logaddexp2_backward_all(grad, self_, other, keyset):
    from .._backends.autograd import _logaddexp2_backward
    return _logaddexp2_backward(grad, self_, other, self_, other, keyset)


def _atan2_backward_all(grad, self_, other, keyset):
    from .._backends.autograd import _atan2_backward
    return _atan2_backward(grad, self_, other, self_, other, keyset)


def _inner_backward_all(grad, self_, other, keyset):
    from .._backends.autograd import _inner_backward
    return _inner_backward(grad, self_, other, self_, other, keyset)


# ---------------------------------------------------------------------------
# Unary-args backward helpers (Batch 3)
# ---------------------------------------------------------------------------

def _clamp_backward_helper(grad, input_, min_val, max_val, keyset):
    from .._backends.autograd import _clamp_backward
    args = (min_val, max_val) if min_val is not None or max_val is not None else ()
    kwargs = {}
    if not args:
        kwargs['min_val'] = min_val
        kwargs['max_val'] = max_val
    return _clamp_backward(grad, input_, input_, keyset, args, kwargs)[0]


def _clamp_min_backward_helper(grad, input_, min_val, keyset):
    from .._backends.autograd import _clamp_min_backward
    return _clamp_min_backward(grad, input_, input_, keyset, (min_val,), {})[0]


def _clamp_max_backward_helper(grad, input_, max_val, keyset):
    from .._backends.autograd import _clamp_max_backward
    return _clamp_max_backward(grad, input_, input_, keyset, (max_val,), {})[0]


def _gather_backward_helper(grad, input_, dim, index, keyset):
    from .._backends.autograd import _gather_backward
    return _gather_backward(grad, input_, input_, keyset, (dim, index), {})[0]


def _index_select_backward_helper(grad, input_, dim, index, keyset):
    from .._backends.autograd import _index_select_backward
    return _index_select_backward(grad, input_, input_, keyset, (dim, index), {})[0]


def _repeat_backward_helper(grad, input_, repeats, keyset):
    from .._backends.autograd import _repeat_backward
    return _repeat_backward(grad, input_, input_, keyset, (repeats,), {})[0]


def _norm_backward_helper(grad, input_, p, dim, keepdim, keyset):
    from .._backends.autograd import _norm_backward
    return _norm_backward(grad, input_, input_, keyset, (p,), {"dim": dim, "keepdim": keepdim})[0]


def _prod_backward_helper(grad, input_, dim, keepdim, keyset):
    from .._backends.autograd import _prod_backward
    return _prod_backward(grad, input_, input_, keyset, (), {"dim": dim, "keepdim": keepdim})[0]


def _cumsum_backward_helper(grad, input_, dim, keyset):
    from .._backends.autograd import _cumsum_backward
    return _cumsum_backward(grad, input_, input_, keyset, (dim,), {})[0]


def _pad_backward_helper(grad, input_, pad, keyset):
    from .._backends.autograd import _pad_backward
    return _pad_backward(grad, input_, input_, keyset, (pad,), {})[0]


def _roll_backward_helper(grad, input_, shifts, dims, keyset):
    from .._backends.autograd import _roll_backward
    return _roll_backward(grad, input_, input_, keyset, (shifts, dims) if dims is not None else (shifts,), {"dims": dims} if dims is not None else {})[0]


def _tile_backward_helper(grad, input_, dims, keyset):
    from .._backends.autograd import _tile_backward
    return _tile_backward(grad, input_, input_, keyset, (dims,), {})[0]


def _movedim_backward_helper(grad, input_, source, destination, keyset):
    from .._backends.autograd import _movedim_backward
    return _movedim_backward(grad, input_, input_, keyset, (source, destination), {})[0]


def _diagonal_backward_helper(grad, input_, offset, dim1, dim2, keyset):
    from .._backends.autograd import _diagonal_backward
    return _diagonal_backward(grad, input_, input_, keyset, (offset, dim1, dim2), {})[0]


def _threshold_backward_helper(grad, input_, threshold, keyset):
    from .._backends.autograd import _threshold_backward
    return _threshold_backward(grad, input_, input_, keyset, (threshold,), {})[0]


def _instance_norm_backward_helper(grad, input_, weight, bias, running_mean, running_var, use_input_stats, momentum, eps, cudnn_enabled, keyset):
    from .._backends.autograd import _instance_norm_backward
    args = (weight, bias, running_mean, running_var, use_input_stats, momentum, eps, cudnn_enabled)
    return _instance_norm_backward(grad, input_, input_, keyset, args, {})[0]


def _normalize_backward_helper(grad, input_, p, dim, eps, keyset):
    from .._backends.autograd import _normalize_backward
    return _normalize_backward(grad, input_, input_, keyset, (p, dim, eps), {})[0]


def _cumprod_backward_helper(grad, input_, dim, keyset):
    from .._backends.autograd import _cumprod_backward
    return _cumprod_backward(grad, input_, input_, keyset, (dim,), {})[0]


def _repeat_interleave_backward_helper(grad, input_, repeats, dim, keyset):
    from .._backends.autograd import _repeat_interleave_backward
    return _repeat_interleave_backward(grad, input_, input_, keyset, (repeats,), {"dim": dim})[0]


def _rot90_backward_helper(grad, input_, k, dims, keyset):
    from .._backends.autograd import _rot90_backward
    return _rot90_backward(grad, input_, input_, keyset, (k, dims), {})[0]


def _take_backward_helper(grad, input_, index, keyset):
    from .._backends.autograd import _take_backward
    return _take_backward(grad, input_, input_, keyset, (index,), {})[0]


def _take_along_dim_backward_helper(grad, input_, indices, dim, keyset):
    from .._backends.autograd import _take_along_dim_backward
    return _take_along_dim_backward(grad, input_, input_, keyset, (indices, dim), {})[0]


def _hardshrink_backward_helper(grad, input_, lambd, keyset):
    from .._backends.autograd import _hardshrink_backward
    return _hardshrink_backward(grad, input_, input_, keyset, (lambd,), {})[0]


def _softshrink_backward_helper(grad, input_, lambd, keyset):
    from .._backends.autograd import _softshrink_backward
    return _softshrink_backward(grad, input_, input_, keyset, (lambd,), {})[0]


def _logsumexp_backward_helper(grad, input_, dim, keepdim, keyset):
    from .._backends.autograd import _logsumexp_backward
    return _logsumexp_backward(grad, input_, input_, keyset, (dim,), {"keepdim": keepdim})[0]


def _renorm_backward_helper(grad, input_, p, dim, maxnorm, keyset):
    from .._backends.autograd import _renorm_backward
    return _renorm_backward(grad, input_, input_, keyset, (p, dim, maxnorm), {})[0]


def _unfold_backward_helper(grad, input_, dimension, size, step, keyset):
    from .._backends.autograd import _unfold_backward
    return _unfold_backward(grad, input_, input_, keyset, (dimension, size, step), {})[0]


def _var_backward_helper(grad, input_, dim, unbiased, keepdim, keyset):
    from .._backends.autograd import _var_backward
    return _var_backward(grad, input_, input_, keyset, (), {"dim": dim, "unbiased": unbiased, "keepdim": keepdim})[0]


def _std_backward_helper(grad, input_, dim, keepdim, unbiased, keyset):
    from .._backends.autograd import _std_backward
    return _std_backward(grad, input_, input_, keyset, (), {"dim": dim, "keepdim": keepdim, "unbiased": unbiased})[0]


def _amax_backward_helper(grad, input_, dim, keepdim, keyset):
    from .._backends.autograd import _amax_backward
    return _amax_backward(grad, input_, input_, keyset, (dim,) if dim is not None else (), {"dim": dim, "keepdim": keepdim})[0]


def _amin_backward_helper(grad, input_, dim, keepdim, keyset):
    from .._backends.autograd import _amin_backward
    return _amin_backward(grad, input_, input_, keyset, (dim,) if dim is not None else (), {"dim": dim, "keepdim": keepdim})[0]


def _narrow_backward_helper(grad, input_, dim, start, length, keyset):
    from .._backends.autograd import _narrow_backward
    return _narrow_backward(grad, input_, input_, keyset, (dim, start, length), {})[0]


def _select_backward_helper(grad, input_, dim, index, keyset):
    from .._backends.autograd import _select_backward
    return _select_backward(grad, input_, input_, keyset, (dim, index), {})[0]


def _masked_fill_backward_helper(grad, input_, mask, keyset):
    from .._backends.autograd import _masked_fill_backward
    return _masked_fill_backward(grad, input_, input_, keyset, (mask,), {})[0]


def _diff_backward_helper(grad, input_, n, dim, keyset):
    from .._backends.autograd import _diff_backward
    return _diff_backward(grad, input_, input_, keyset, (n, dim), {})[0]


def _trace_backward_helper(grad, input_, keyset):
    from .._backends.autograd import _trace_backward
    return _trace_backward(grad, input_, input_, keyset, (), {})[0]


def _det_backward_helper(grad, input_, keyset):
    from .._backends.autograd import _det_backward
    return _det_backward(grad, input_, input_, keyset, (), {})[0]


def _diag_backward_helper(grad, input_, diagonal, keyset):
    from .._backends.autograd import _diag_backward
    return _diag_backward(grad, input_, input_, keyset, (diagonal,), {})[0]


def _im2col_backward_helper(grad, input_, kernel_size, dilation, padding, stride, keyset):
    from .._backends.autograd import _im2col_backward
    return _im2col_backward(grad, input_, input_, keyset, (kernel_size, dilation, padding, stride), {})[0]


def _col2im_backward_helper(grad, input_, output_size, kernel_size, dilation, padding, stride, keyset):
    from .._backends.autograd import _col2im_backward
    return _col2im_backward(grad, input_, input_, keyset, (output_size, kernel_size, dilation, padding, stride), {})[0]


def _nansum_backward_helper(grad, input_, dim, keepdim, keyset):
    from .._backends.autograd import _nansum_backward
    return _nansum_backward(grad, input_, input_, keyset, (), {"dim": dim, "keepdim": keepdim})[0]


def _nanmean_backward_helper(grad, input_, dim, keepdim, keyset):
    from .._backends.autograd import _nanmean_backward
    return _nanmean_backward(grad, input_, input_, keyset, (), {"dim": dim, "keepdim": keepdim})[0]


def _matrix_power_backward_helper(grad, input_, n, keyset):
    from .._backends.autograd import _matrix_power_backward
    return _matrix_power_backward(grad, input_, input_, keyset, (n,), {})[0]


def _special_logit_backward_helper(grad, input_, eps, keyset):
    from .._backends.autograd import _special_logit_backward
    return _special_logit_backward(grad, input_, input_, keyset, (eps,) if eps is not None else (), {"eps": eps} if eps is not None else {})[0]


def _linalg_norm_backward_helper(grad, input_, ord, dim, keepdim, keyset):
    from .._backends.autograd import _linalg_norm_backward
    return _linalg_norm_backward(grad, input_, input_, keyset, (ord,), {"dim": dim, "keepdim": keepdim})[0]


def _linalg_vector_norm_backward_helper(grad, input_, ord, dim, keepdim, keyset):
    from .._backends.autograd import _linalg_vector_norm_backward
    return _linalg_vector_norm_backward(grad, input_, input_, keyset, (ord,), {"dim": dim, "keepdim": keepdim})[0]


def _linalg_matrix_norm_backward_helper(grad, input_, ord, dim, keepdim, keyset):
    from .._backends.autograd import _linalg_matrix_norm_backward
    return _linalg_matrix_norm_backward(grad, input_, input_, keyset, (ord,), {"dim": dim, "keepdim": keepdim})[0]


def _linalg_pinv_backward_helper(grad, input_, atol, rtol, hermitian, keyset):
    from .._backends.autograd import _linalg_pinv_backward
    return _linalg_pinv_backward(grad, input_, input_, keyset, (atol, rtol, hermitian), {})[0]


def _linalg_cond_backward_helper(grad, input_, p, keyset):
    from .._backends.autograd import _linalg_cond_backward
    return _linalg_cond_backward(grad, input_, input_, keyset, (p,) if p is not None else (), {})[0]


def _linalg_matrix_exp_backward_helper(grad, input_, keyset):
    from .._backends.autograd import _linalg_matrix_exp_backward
    return _linalg_matrix_exp_backward(grad, input_, input_, keyset, (), {})[0]


def _linalg_tensorinv_backward_helper(grad, input_, ind, keyset):
    from .._backends.autograd import _linalg_tensorinv_backward
    return _linalg_tensorinv_backward(grad, input_, input_, keyset, (ind,), {})[0]


def _linalg_vander_backward_helper(grad, x, N, keyset):
    from .._backends.autograd import _linalg_vander_backward
    return _linalg_vander_backward(grad, x, x, keyset, (N,) if N is not None else (), {"N": N})[0]


def _linalg_eigvalsh_backward_helper(grad, input_, UPLO, keyset):
    from .._backends.autograd import _linalg_eigvalsh_backward
    return _linalg_eigvalsh_backward(grad, input_, input_, keyset, (UPLO,), {})[0]


def _sum_to_size_backward_helper(grad, input_, size, keyset):
    from .._backends.autograd import _sum_to_size_backward
    return _sum_to_size_backward(grad, input_, input_, keyset, (size,), {})[0]


def _slice_backward_helper(grad, input_, dim, start, end, step, keyset):
    from .._backends.autograd import _slice_backward
    return _slice_backward(grad, input_, input_, keyset, (dim, start, end, step), {})[0]


def _getitem_backward_helper(grad, self_, key, keyset):
    from .._backends.autograd import _getitem_backward
    return _getitem_backward(grad, self_, self_, keyset, (key,), {})[0]


def _to_backward_helper(grad, input_, keyset):
    from .._backends.autograd import _to_backward
    return _to_backward(grad, input_, input_, keyset, (), {})[0]


def _quantile_backward_helper(grad, input_, q, dim, keepdim, keyset):
    from .._backends.autograd import _quantile_backward
    args = (q,)
    if dim is not None:
        args = (q, dim)
    return _quantile_backward(grad, input_, input_, keyset, args, {"dim": dim, "keepdim": keepdim})[0]


# ---------------------------------------------------------------------------
# Special function backward helpers (Batch 4)
# ---------------------------------------------------------------------------

def _special_erfinv_grad(grad, self_, keyset):
    from .._backends.autograd import _special_erfinv_backward
    return _special_erfinv_backward(grad, self_, self_, keyset)[0]


def _special_erfcx_grad(grad, self_, keyset):
    from .._backends.autograd import _special_erfcx_backward
    return _special_erfcx_backward(grad, self_, self_, keyset)[0]


def _special_ndtr_grad(grad, self_, keyset):
    from .._backends.autograd import _special_ndtr_backward
    return _special_ndtr_backward(grad, self_, self_, keyset)[0]


def _special_ndtri_grad(grad, self_, keyset):
    from .._backends.autograd import _special_ndtri_backward
    return _special_ndtri_backward(grad, self_, self_, keyset)[0]


def _special_sinc_grad(grad, self_, keyset):
    from .._backends.autograd import _special_sinc_backward
    return _special_sinc_backward(grad, self_, self_, keyset)[0]


def _special_entr_grad(grad, self_, keyset):
    from .._backends.autograd import _special_entr_backward
    return _special_entr_backward(grad, self_, self_, keyset)[0]


def _special_log_ndtr_grad(grad, self_, keyset):
    from .._backends.autograd import _special_log_ndtr_backward
    return _special_log_ndtr_backward(grad, self_, self_, keyset)[0]


def _special_i0e_grad(grad, self_, keyset):
    from .._backends.autograd import _special_i0e_backward
    return _special_i0e_backward(grad, self_, self_, keyset)[0]


def _special_i1_grad(grad, self_, keyset):
    from .._backends.autograd import _special_i1_backward
    return _special_i1_backward(grad, self_, self_, keyset)[0]


def _special_i1e_grad(grad, self_, keyset):
    from .._backends.autograd import _special_i1e_backward
    return _special_i1e_backward(grad, self_, self_, keyset)[0]


def _special_xlogy_backward_all(grad, self_, other, keyset):
    from .._backends.autograd import _special_xlogy_backward
    return _special_xlogy_backward(grad, self_, other, self_, other, keyset)


def _special_xlog1py_backward_all(grad, self_, other, keyset):
    from .._backends.autograd import _special_xlog1py_backward
    return _special_xlog1py_backward(grad, self_, other, self_, other, keyset)


def _special_zeta_backward_all(grad, self_, other, keyset):
    from .._backends.autograd import _special_zeta_backward
    return _special_zeta_backward(grad, self_, other, self_, other, keyset)


def _special_gammainc_backward_all(grad, self_, other, keyset):
    from .._backends.autograd import _special_gammainc_backward
    return _special_gammainc_backward(grad, self_, other, self_, other, keyset)


def _special_gammaincc_backward_all(grad, self_, other, keyset):
    from .._backends.autograd import _special_gammaincc_backward
    return _special_gammaincc_backward(grad, self_, other, self_, other, keyset)


def _linalg_inv_grad(grad, self_, keyset):
    from .._backends.autograd import _linalg_inv_backward
    return _linalg_inv_backward(grad, self_, self_, keyset)[0]


def _linalg_svdvals_grad(grad, self_, keyset):
    from .._backends.autograd import _linalg_svdvals_backward
    return _linalg_svdvals_backward(grad, self_, self_, keyset)[0]


# ---------------------------------------------------------------------------
# FFT backward helpers (Batch 5)
# ---------------------------------------------------------------------------

def _fft_c2c_backward_helper(grad, input_, n, dim, norm, inverse_op, keyset):
    return redispatch(inverse_op, keyset, grad, n=n, dim=dim, norm=norm)


def _fft_r2c_backward_helper(grad, input_, n, dim, norm, inverse_op, keyset):
    result = redispatch(inverse_op, keyset, grad, n=n if n is not None else input_.shape[dim if isinstance(dim, int) else -1], dim=dim, norm=norm)
    return result


def _fft_c2r_backward_helper(grad, input_, n, dim, norm, inverse_op, keyset):
    return redispatch(inverse_op, keyset, grad, dim=dim, norm=norm)


def _fft_shift_backward_helper(grad, input_, dim, inverse_op, keyset):
    return redispatch(inverse_op, keyset, grad, dim=dim)


# ---------------------------------------------------------------------------
# Linalg custom backward helpers (Batch 5)
# ---------------------------------------------------------------------------

def _linalg_det_backward_helper(grad, self_, keyset):
    from .._backends.autograd import _linalg_det_backward
    return _linalg_det_backward(grad, self_, self_, keyset)[0]


def _linalg_slogdet_backward_helper(grad, self_, keyset):
    from .._backends.autograd import _linalg_slogdet_backward
    return _linalg_slogdet_backward(grad, self_, self_, keyset)[0]


def _linalg_cholesky_backward_helper(grad, self_, upper, keyset):
    from .._backends.autograd import _linalg_cholesky_backward
    return _linalg_cholesky_backward(grad, self_, self_, keyset, (upper,))[0]


def _linalg_solve_backward_all(grad, self_, other, left, keyset):
    from .._backends.autograd import _linalg_solve_backward
    return _linalg_solve_backward(grad, self_, other, self_, other, keyset, (left,))


def _linalg_solve_triangular_backward_all(grad, self_, B, upper, left, unitriangular, keyset):
    from .._backends.autograd import _linalg_solve_triangular_backward
    return _linalg_solve_triangular_backward(grad, self_, B, self_, B, keyset, (upper, left, unitriangular))


def _linalg_qr_backward_helper(grad, self_, mode, keyset):
    from .._backends.autograd import _linalg_qr_backward
    return _linalg_qr_backward(grad, self_, self_, keyset, (mode,))[0]


def _linalg_svd_backward_helper(grad, self_, full_matrices, keyset):
    from .._backends.autograd import _linalg_svd_backward
    return _linalg_svd_backward(grad, self_, self_, keyset, (full_matrices,))[0]


def _linalg_eigh_backward_helper(grad, self_, UPLO, keyset):
    from .._backends.autograd import _linalg_eigh_backward
    return _linalg_eigh_backward(grad, self_, self_, keyset, (UPLO,))[0]


def _linalg_eig_backward_helper(grad, self_, keyset):
    from .._backends.autograd import _linalg_eig_backward
    return _linalg_eig_backward(grad, self_, self_, keyset)[0]


def _linalg_lu_backward_helper(grad, self_, pivot, keyset):
    from .._backends.autograd import _linalg_lu_backward
    return _linalg_lu_backward(grad, self_, self_, keyset, (pivot,))[0]


def _linalg_lu_factor_backward_helper(grad, self_, pivot, keyset):
    from .._backends.autograd import _linalg_lu_factor_backward
    return _linalg_lu_factor_backward(grad, self_, self_, keyset, (pivot,))[0]


def _linalg_lu_solve_backward_all(grad, LU, pivots, B, left, adjoint, keyset):
    from .._backends.autograd import _linalg_lu_solve_backward
    return _linalg_lu_solve_backward(grad, LU, pivots, B, LU, pivots, B, keyset, (left, adjoint))


def _linalg_multi_dot_backward_helper(grad, tensors, keyset):
    from .._backends.autograd import _linalg_multi_dot_backward
    return _linalg_multi_dot_backward(grad, tensors, keyset)


# ---------------------------------------------------------------------------
# Special custom backward helpers (Batch 5)
# ---------------------------------------------------------------------------

def _special_polygamma_backward_helper(grad, n, self_, keyset):
    return redispatch("mul", keyset, grad, redispatch("special_polygamma", keyset, n + 1, self_))


def _special_multigammaln_backward_helper(grad, self_, p, keyset):
    from .._backends.autograd import _special_multigammaln_backward
    return _special_multigammaln_backward(grad, self_, self_, keyset, (p,))[0]


# ---------------------------------------------------------------------------
# Multi-tensor backward helpers (Batch 6)
# ---------------------------------------------------------------------------

def _lerp_backward_all(grad, self_, other, weight, keyset):
    from .._backends.autograd import _lerp_backward
    return _lerp_backward(grad, self_, other, weight, keyset)


def _addcmul_backward_all(grad, self_, tensor1, tensor2, value, keyset):
    from .._backends.autograd import _addcmul_backward
    return _addcmul_backward(grad, self_, tensor1, tensor2, value, keyset)


def _addcdiv_backward_all(grad, self_, tensor1, tensor2, value, keyset):
    from .._backends.autograd import _addcdiv_backward
    return _addcdiv_backward(grad, self_, tensor1, tensor2, value, keyset)


def _addmm_backward_all(grad, self_, mat1, mat2, beta, alpha, keyset):
    from .._backends.autograd import _addmm_backward
    return _addmm_backward(grad, self_, mat1, mat2, beta, alpha, keyset)


def _baddbmm_backward_all(grad, self_, batch1, batch2, beta, alpha, keyset):
    from .._backends.autograd import _baddbmm_backward
    return _baddbmm_backward(grad, self_, batch1, batch2, beta, alpha, keyset)


def _where_backward_all(grad, condition, self_, other, keyset):
    from .._backends.autograd import _where_backward
    return _where_backward(grad, condition, self_, other, condition, keyset)[1:]


def _embedding_backward_helper(grad, weight, indices, padding_idx, scale_grad_by_freq, keyset):
    from .._backends.autograd import _embedding_backward
    return _embedding_backward(grad, weight, indices, weight, indices, keyset,
                               padding_idx=padding_idx, scale_grad_by_freq=scale_grad_by_freq)[0]


def _cross_backward_all(grad, self_, other, dim, keyset):
    from .._backends.autograd import _cross_backward
    return _cross_backward(grad, self_, other, self_, other, keyset, (dim,))


def _min_backward_all(grad, self_, other, keyset):
    from .._backends.autograd import _min_backward
    return _min_backward(grad, self_, other, self_, other, keyset)


def _max_backward_all(grad, self_, other, keyset):
    from .._backends.autograd import _max_backward
    return _max_backward(grad, self_, other, self_, other, keyset)


def _dist_backward_all(grad, self_, other, p, keyset):
    from .._backends.autograd import _dist_backward
    return _dist_backward(grad, self_, other, self_, other, keyset, (p,))


def _cdist_backward_all(grad, self_, other, p, keyset):
    from .._backends.autograd import _cdist_backward
    return _cdist_backward(grad, self_, other, self_, other, keyset, (p,))


def _as_strided_scatter_backward_all(grad, self_, src, size, stride, storage_offset, keyset):
    from .._backends.autograd import _as_strided_scatter_backward
    return _as_strided_scatter_backward(grad, self_, src, self_, src, keyset, (size, stride, storage_offset))
'''


# Python keywords that cannot be used as parameter names
_PYTHON_KEYWORDS = {"self", "cls", "input", "None", "True", "False", "return", "class", "def", "if", "else", "for", "while", "import", "from", "in", "is", "not", "and", "or"}


def _safe_param(name: str) -> str:
    """Make a name safe for use as a keyword parameter."""
    if name in _PYTHON_KEYWORDS:
        return name + "_"
    return name


def _safe_local(name: str) -> str:
    """Make a name safe for use as a local variable in apply()."""
    if name in _PYTHON_KEYWORDS:
        return name + "_"
    return name


def _gen_one_node(info: DifferentiabilityInfo) -> str:
    cls_name = info.backward_name
    saved_inputs = info.all_saved_inputs
    saved_outputs = info.all_saved_outputs
    non_tensor_args = info.non_tensor_args

    lines: list[str] = []
    lines.append(f"\nclass {cls_name}(Node):")

    # __init__
    lines.append("    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):")
    lines.append(f"        super().__init__(None, inputs, name={cls_name!r})")
    lines.append("        self._raw_keyset = raw_keyset")
    lines.append("        self._active_keyset = active_keyset")
    # Slots for saved tensor indices
    for name in saved_inputs:
        lines.append(f"        self._saved_{name}_idx = None")
    for name in saved_outputs:
        lines.append(f"        self._saved_{name}_idx = None")
    # Slots for non-tensor args
    for arg in non_tensor_args:
        lines.append(f"        self._{arg.name} = None")

    # save_for_backward — use safe param names to avoid shadowing `self`
    all_saved = saved_inputs + saved_outputs
    if all_saved:
        kw_params = ", ".join(f"{_safe_param(n)}=None" for n in all_saved)
        lines.append(f"\n    def _save(self, *, {kw_params}):")
        lines.append("        tensors = []")
        for name in all_saved:
            p = _safe_param(name)
            lines.append(f"        if {p} is not None:")
            lines.append(f"            self._saved_{name}_idx = len(tensors)")
            lines.append(f"            tensors.append({p})")
        lines.append("        if tensors:")
        lines.append("            super().save_for_backward(*tensors)")
        # Populate _saved_fields so Node.__getattr__ can resolve _raw_saved_* / _saved_*
        for name in all_saved:
            lines.append(f"        if self._saved_{name}_idx is not None:")
            lines.append(f"            self._saved_fields[{name!r}] = self._saved_tensors_list[self._saved_{name}_idx]")

    # backward method (overrides Node.backward directly — no bound-method cycle)
    lines.append("\n    def backward(self, grad):")
    lines.append("        from .._dispatch.dispatcher import current_dispatch_keyset")
    lines.append("        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)")

    # Retrieve saved tensors — use safe local names
    # Build set of optional tensor names for conditional access
    optional_tensor_names = {a.name for a in info.args if a.is_optional_tensor}
    if all_saved:
        lines.append("        _saved = self.saved_tensors()")
    for name in saved_inputs:
        local = _safe_local(name)
        if name in optional_tensor_names:
            lines.append(f"        {local} = _saved[self._saved_{name}_idx] if self._saved_{name}_idx is not None else None")
        else:
            lines.append(f"        {local} = _saved[self._saved_{name}_idx]")
    for name in saved_outputs:
        local = _safe_local(name)
        lines.append(f"        {local} = _saved[self._saved_{name}_idx]")

    # Retrieve unsaved tensor args from self.inputs (when save_inputs override excludes them)
    # Build map of tensor arg name -> index in the inputs tuple
    tensor_args = [a for a in info.args if a.is_tensor or a.is_optional_tensor]
    tensor_arg_indices = {a.name: i for i, a in enumerate(tensor_args)}
    saved_set = set(saved_inputs) | set(saved_outputs)
    # Collect all tensor arg names referenced in any formula
    import re as _re
    _ident_pat = _re.compile(r"\b([a-zA-Z_]\w*)\b")
    formula_referenced = set()
    for d in info.derivatives:
        formula_referenced |= set(_ident_pat.findall(d.formula))
    tensor_arg_names = {a.name for a in tensor_args}
    unsaved_referenced = (formula_referenced & tensor_arg_names) - saved_set
    for name in sorted(unsaved_referenced):
        local = _safe_local(name)
        idx = tensor_arg_indices[name]
        lines.append(f"        {local} = self.inputs[{idx}]")

    # Retrieve non-tensor args
    for arg in non_tensor_args:
        lines.append(f"        {arg.name} = self._{arg.name}")

    # Generate gradient computation — rewrite `self` references in formulas
    lines.append("        with _grad_context(keyset):")

    grad_vars: dict[str, str] = {}
    for deriv in info.derivatives:
        formula = deriv.formula
        # Replace bare `self` references with `self_` in the formula
        formula = _rewrite_keyword_refs(formula)
        if len(deriv.var_names) == 1:
            var_name = deriv.var_names[0]
            grad_var = f"grad_{var_name}"
            grad_vars[var_name] = grad_var
            lines.append(f"            {grad_var} = {formula}")
        else:
            # Multi-output: tuple unpacking (e.g. conv backward returns all grads at once)
            grad_var_names = [f"grad_{v}" for v in deriv.var_names]
            for v, gv in zip(deriv.var_names, grad_var_names):
                grad_vars[v] = gv
            lhs = ", ".join(grad_var_names)
            lines.append(f"            {lhs} = {formula}")

    # Build return tuple in argument order
    diff_inputs = info.differentiable_inputs
    if len(diff_inputs) == 0:
        lines.append("        return (grad,)")
    else:
        ret_parts = []
        for arg in info.tensor_args:
            if arg.name in grad_vars:
                ret_parts.append(grad_vars[arg.name])
            elif arg.name in info.non_differentiable:
                ret_parts.append("None")
            else:
                ret_parts.append("None")
        lines.append(f"        return ({', '.join(ret_parts)},)")

    return "\n".join(lines)


def _rewrite_keyword_refs(formula: str) -> str:
    """Replace Python keywords used as parameter names with their safe versions.

    e.g. `self` -> `self_`, `input` -> `input_` in formulas,
    so they match the local variable names generated by _safe_local().
    """
    import re
    for kw in _PYTHON_KEYWORDS:
        if kw in ("None", "True", "False"):
            continue  # These are actual Python constants, not parameter names
        formula = re.sub(r'\b' + kw + r'\b', kw + '_', formula)
    return formula
