"""Generate registration code that wires generated wrappers into the dispatcher."""
from __future__ import annotations

from .model import DifferentiabilityInfo


def gen_registration(infos: list[DifferentiabilityInfo]) -> str:
    """Generate registration.py source."""
    parts = [_HEADER]
    parts.append("\n\ndef register_generated_autograd_kernels():")
    parts.append("    from .._dispatch.registration import register_autograd_kernels")
    parts.append("    from . import variable_type as _VT\n")
    for info in infos:
        func_name = f"{info.op_name}_autograd"
        op = info.op_name
        parts.append(f"    register_autograd_kernels({op!r}, default=_VT.{func_name}, cpu=_VT.{func_name}, cuda=_VT.{func_name}, npu=_VT.{func_name}, meta=_VT.{func_name})")
    parts.append("")
    return "\n".join(parts)


_HEADER = '''\
"""Auto-generated autograd kernel registration — DO NOT EDIT.

Generated by tools/autograd/gen_registration.py from derivatives.yaml.
"""
'''
