#!/usr/bin/env python3
"""Entry script for running PyTorch official tests against candle.

Manages the PyTorch clone, builds pytest commands, and generates
compatibility reports.

Usage:
    python compat/pytorch/run.py                              # tier1_mechanism
    python compat/pytorch/run.py --tier mechanism:2           # tier1+2 mechanism
    python compat/pytorch/run.py --tier gpu:1                 # CUDA->NPU
    python compat/pytorch/run.py --file test_tensor.py        # single file
    python compat/pytorch/run.py --file test_tensor.py -k add # single test
    python compat/pytorch/run.py --summarize report.json      # view report
    python compat/pytorch/run.py --setup-only                 # clone only
    python compat/pytorch/run.py --gate-only                  # only run pass_gate tests
"""
import argparse
import json
import os
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path

import yaml

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
COMPAT_DIR = Path(__file__).resolve().parent           # compat/pytorch/
PROJECT_ROOT = COMPAT_DIR.parent.parent                # project root
SRC_DIR = PROJECT_ROOT / "src"
PYTORCH_DIR = COMPAT_DIR / "_pytorch"
REPORTS_DIR = COMPAT_DIR / "_reports"


def load_tests_config():
    """Load and return the tests.yaml configuration."""
    config_path = COMPAT_DIR / "tests.yaml"
    with open(config_path) as f:
        return yaml.safe_load(f)


# ---------------------------------------------------------------------------
# PyTorch clone management
# ---------------------------------------------------------------------------


def _safe_rmtree(path: Path):
    if path.exists():
        shutil.rmtree(path)



def _clone_pytorch_from(url: str, ref: str):
    subprocess.run(
        [
            "git", "clone",
            "--depth", "1",
            "--branch", ref,
            url,
            str(PYTORCH_DIR),
        ],
        check=True,
    )


def setup_pytorch(ref: str):
    """Shallow-clone PyTorch at the given ref if not already present."""
    if PYTORCH_DIR.exists():
        # Check if already at the right ref
        result = subprocess.run(
            ["git", "-C", str(PYTORCH_DIR), "describe", "--tags", "--exact-match"],
            capture_output=True, text=True,
        )
        if result.returncode == 0 and result.stdout.strip() == ref:
            print(f"[compat] pytorch already at {ref}")
            return
        # Wrong ref -- re-clone
        print(f"[compat] pytorch ref mismatch, re-cloning at {ref}")
        _safe_rmtree(PYTORCH_DIR)

    clone_sources = [
        "https://gitee.com/mirrors/pytorch",
        "https://github.com/pytorch/pytorch",
    ]

    last_error = None
    for i, url in enumerate(clone_sources, start=1):
        print(f"[compat] cloning pytorch at {ref} from {url} ...")
        try:
            _clone_pytorch_from(url, ref)
            print(f"[compat] pytorch {ref} ready")
            return
        except subprocess.CalledProcessError as exc:
            last_error = exc
            print(f"[compat] clone attempt {i} failed from {url}: {exc}")
            _safe_rmtree(PYTORCH_DIR)

    raise last_error

_BRIDGE_CONFTEST = textwrap.dedent("""\
    # Auto-generated by compat/pytorch/run.py -- do not edit
    import importlib.util
    import os
    from pathlib import Path

    # Activate candle's torch compatibility finder if USE_CANDLE is set
    if os.environ.get("USE_CANDLE", "").lower() in ("1", "true", "yes"):
        import _candle_torch_compat
        if not _candle_torch_compat.is_active():
            _candle_torch_compat._install()

    _compat_dir = Path({compat_dir!r})
    _spec = importlib.util.spec_from_file_location(
        "pytorch_compat_conftest", str(_compat_dir / "conftest.py"))
    _mod = importlib.util.module_from_spec(_spec)
    _spec.loader.exec_module(_mod)

    pytest_collection_modifyitems = _mod.pytest_collection_modifyitems
""")


def write_bridge_conftest():
    """Write a conftest.py into the pytorch test/ directory."""
    tests_dir = PYTORCH_DIR / "test"
    bridge_path = tests_dir / "conftest.py"
    content = _BRIDGE_CONFTEST.format(compat_dir=str(COMPAT_DIR))
    bridge_path.write_text(content)
    return bridge_path


# ---------------------------------------------------------------------------
# Tier / file selection
# ---------------------------------------------------------------------------

def parse_tier_spec(tier_spec: str) -> tuple[str, int]:
    """Parse a tier spec like 'mechanism:2' into (category, level).

    Returns:
        (category, level) where category is one of:
        'mechanism', 'gpu', 'mps', 'distributed'
    """
    if ":" in tier_spec:
        category, level_str = tier_spec.split(":", 1)
        level = int(level_str)
    else:
        # Bare category name means level 1
        category = tier_spec
        level = 1
    return category, level


def get_test_files_for_tier(config: dict, category: str, level: int) -> list[str]:
    """Return test file paths for the given tier category and level (inclusive).

    For 'mechanism' and 'gpu', levels are cumulative (level 2 includes level 1).
    For 'mps' and 'distributed', there's only one level.
    """
    tests_dir = PYTORCH_DIR / "test"
    filenames = []

    if category in ("mechanism", "gpu"):
        for lvl in range(1, level + 1):
            key = f"tier{lvl}_{category}"
            filenames.extend(config.get(key, []))
    elif category in ("mps", "distributed"):
        filenames.extend(config.get(category, []))
    else:
        print(f"[compat] WARNING: unknown tier category '{category}'")
        return []

    # Map filenames to full paths
    files = []
    for fname in filenames:
        test_path = tests_dir / fname
        if test_path.exists():
            files.append(str(test_path))
        else:
            print(f"[compat] WARNING: test file not found: {test_path}")
    return files


def get_test_files_by_name(filenames: list[str]) -> list[str]:
    """Map test file names to paths under _pytorch/test/."""
    tests_dir = PYTORCH_DIR / "test"
    files = []
    for fname in filenames:
        test_path = tests_dir / fname
        if test_path.exists():
            files.append(str(test_path))
        else:
            print(f"[compat] WARNING: test file not found: {test_path}")
    return files


# ---------------------------------------------------------------------------
# Build pytest command
# ---------------------------------------------------------------------------

def build_pytest_args(
    test_files: list[str],
    config: dict,
    json_report: str | None = None,
    extra_args: list[str] | None = None,
) -> list[str]:
    """Build the full pytest argument list."""
    args = [sys.executable, "-m", "pytest"]

    # Prevent pytest from loading conftest.py files above the test/ dir
    tests_dir = str(PYTORCH_DIR / "test")
    args.extend(["--confcutdir", tests_dir])

    # Don't abort on collection errors -- report them and keep going
    args.append("--continue-on-collection-errors")

    # Build a combined -k expression for deselect patterns
    deselect_parts = []
    for pattern in config.get("deselect_patterns", []):
        deselect_parts.append(_pattern_to_k_expr(pattern))

    # Merge with any user -k from extra_args
    user_k = None
    if extra_args:
        filtered_extra = []
        i = 0
        while i < len(extra_args):
            if extra_args[i] == "-k" and i + 1 < len(extra_args):
                user_k = extra_args[i + 1]
                i += 2
            else:
                filtered_extra.append(extra_args[i])
                i += 1
        extra_args = filtered_extra

    if deselect_parts or user_k:
        parts = [f"not ({p})" for p in deselect_parts]
        if user_k:
            parts.append(f"({user_k})")
        k_expr = " and ".join(parts)
        args.extend(["-k", k_expr])

    # Skip markers via -m
    skip_markers = config.get("skip_markers", [])
    if skip_markers:
        m_expr = " and ".join(f"not {m}" for m in skip_markers)
        args.extend(["-m", m_expr])

    # JSON report
    if json_report:
        args.extend(["--json-report", f"--json-report-file={json_report}"])

    # Test files
    args.extend(test_files)

    # Extra user args (-v, --tb=short, etc.)
    if extra_args:
        args.extend(extra_args)

    return args


def _pattern_to_k_expr(pattern: str) -> str:
    """Convert a glob-like deselect pattern to a pytest -k expression.

    e.g. "*dynamo*" -> "dynamo"
    """
    return pattern.strip("*")


# ---------------------------------------------------------------------------
# Run tests
# ---------------------------------------------------------------------------

def run_tests(pytest_args: list[str]) -> int:
    """Run pytest as a subprocess with USE_CANDLE=1."""
    env = os.environ.copy()
    env["USE_CANDLE"] = "1"
    # Ensure candle src is on PYTHONPATH
    pythonpath = env.get("PYTHONPATH", "")
    paths = [str(SRC_DIR)]
    if pythonpath:
        paths.append(pythonpath)
    env["PYTHONPATH"] = os.pathsep.join(paths)

    print(f"[compat] running: {' '.join(pytest_args)}")
    result = subprocess.run(pytest_args, env=env)
    return result.returncode


# ---------------------------------------------------------------------------
# Report summarization
# ---------------------------------------------------------------------------

def summarize_report(report_path: str):
    """Print a human-readable summary from a pytest-json-report file."""
    with open(report_path) as f:
        report = json.load(f)

    tests = report.get("tests", [])
    collectors = report.get("collectors", [])

    # Count collection errors
    collection_errors = []
    for c in collectors:
        if c.get("outcome") == "failed":
            nodeid = c.get("nodeid", "")
            longrepr = c.get("longrepr", "")
            collection_errors.append((nodeid, longrepr))

    if not tests and not collection_errors:
        print("[compat] no test results found in report")
        return

    # Group by test file
    file_stats: dict[str, dict] = {}
    for test in tests:
        nodeid = test.get("nodeid", "")
        outcome = test.get("outcome", "unknown")

        # Extract test file name from nodeid
        test_file = _extract_test_file(nodeid)

        if test_file not in file_stats:
            file_stats[test_file] = {
                "total": 0, "passed": 0, "failed": 0,
                "xfailed": 0, "xpassed": 0, "skipped": 0,
            }
        stats = file_stats[test_file]
        stats["total"] += 1
        if outcome == "passed":
            stats["passed"] += 1
        elif outcome == "failed":
            stats["failed"] += 1
        elif outcome == "xfailed":
            stats["xfailed"] += 1
        elif outcome == "xpassed":
            stats["xpassed"] += 1
        elif outcome == "skipped":
            stats["skipped"] += 1

    # Import candle version
    try:
        sys.path.insert(0, str(SRC_DIR))
        import candle
        candle_version = candle.__version__
    except ImportError:
        candle_version = "unknown"

    config = load_tests_config()
    pt_ref = config.get("pytorch_ref", "unknown")

    # Print summary table
    print()
    print("=== Candle x PyTorch Compatibility ===")
    print(f"PyTorch: {pt_ref} | Candle: {candle_version}")
    print()

    header = (
        f"{'Test File':<30} {'Total':>5} {'Pass':>5} {'Fail':>5} "
        f"{'XFail':>5} {'XPass':>5} {'Skip':>5} {'Pass%':>6}"
    )
    print(header)
    print("-" * len(header))

    totals = {
        "total": 0, "passed": 0, "failed": 0,
        "xfailed": 0, "xpassed": 0, "skipped": 0,
    }

    for test_file in sorted(file_stats):
        s = file_stats[test_file]
        pass_pct = (s["passed"] / s["total"] * 100) if s["total"] > 0 else 0
        # Truncate long filenames
        display_name = test_file if len(test_file) <= 28 else "..." + test_file[-25:]
        print(
            f"{display_name:<30} {s['total']:>5} {s['passed']:>5} {s['failed']:>5} "
            f"{s['xfailed']:>5} {s['xpassed']:>5} {s['skipped']:>5} {pass_pct:>5.1f}%"
        )
        for k in totals:
            totals[k] += s[k]

    print("-" * len(header))
    total_pct = (totals["passed"] / totals["total"] * 100) if totals["total"] > 0 else 0
    print(
        f"{'TOTAL':<30} {totals['total']:>5} {totals['passed']:>5} {totals['failed']:>5} "
        f"{totals['xfailed']:>5} {totals['xpassed']:>5} {totals['skipped']:>5} {total_pct:>5.1f}%"
    )
    print()

    if collection_errors:
        print(f"Collection errors: {len(collection_errors)}")
        for nodeid, longrepr in collection_errors:
            # Show first line of the error
            first_line = longrepr.split("\n")[-1] if longrepr else "unknown"
            print(f"  COLLECT ERROR  {nodeid}")
            print(f"                 {first_line}")
        print()


def _extract_test_file(nodeid: str) -> str:
    """Extract test file name from a pytest nodeid.

    e.g. 'test/test_tensor.py::TestTensor::test_add' -> 'test_tensor.py'
    """
    file_part = nodeid.split("::")[0]
    return Path(file_part).name


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Run PyTorch official tests against candle",
    )
    parser.add_argument(
        "--file", type=str, default=None,
        help="Run tests for a single file (e.g., test_tensor.py)",
    )
    parser.add_argument(
        "--tier", type=str, default=None,
        help=(
            "Tier spec: 'mechanism:1' (default), 'mechanism:2', "
            "'gpu:1', 'gpu:2', 'mps', 'distributed'"
        ),
    )
    parser.add_argument(
        "--setup-only", action="store_true",
        help="Only clone PyTorch, don't run tests",
    )
    parser.add_argument(
        "--gate-only", action="store_true",
        help="Only run pass_gate tests from xfail.yaml",
    )
    parser.add_argument(
        "--json-report", type=str, default=None,
        help="Path to write pytest-json-report output",
    )
    parser.add_argument(
        "--summarize", type=str, default=None,
        help="Summarize a previous JSON report file and exit",
    )
    parser.add_argument(
        "--pytorch-ref", type=str, default=None,
        help="Override the PyTorch git ref (default: from tests.yaml)",
    )

    args, extra = parser.parse_known_args()
    # Everything not consumed by our parser is forwarded to pytest
    args.pytest_args = extra

    # Summarize mode: just print and exit
    if args.summarize:
        summarize_report(args.summarize)
        return

    config = load_tests_config()
    ref = args.pytorch_ref or config.get("pytorch_ref", "v2.5.0")

    # Clone / setup
    setup_pytorch(ref)

    if args.setup_only:
        print("[compat] setup complete")
        return

    # Write bridge conftest
    write_bridge_conftest()

    # Determine which test files to run
    if args.file:
        test_files = get_test_files_by_name([args.file])
    elif args.gate_only:
        # Run only the pass_gate tests from xfail.yaml
        xfail_path = COMPAT_DIR / "xfail.yaml"
        with open(xfail_path) as f:
            xfail_cfg = yaml.safe_load(f) or {}
        gate_files = xfail_cfg.get("pass_gate", [])
        if not gate_files:
            print("[compat] no pass_gate entries in xfail.yaml")
            return
        test_files = get_test_files_by_name(gate_files)
    else:
        # Default to tier mechanism:1
        tier_spec = args.tier or "mechanism:1"
        category, level = parse_tier_spec(tier_spec)
        test_files = get_test_files_for_tier(config, category, level)

    if not test_files:
        print("[compat] no test files found")
        sys.exit(1)

    print(f"[compat] testing files: {', '.join(Path(f).name for f in test_files)}")

    # Ensure reports directory exists for json output
    if args.json_report:
        report_path = Path(args.json_report)
        report_path.parent.mkdir(parents=True, exist_ok=True)

    # Build and run pytest
    pytest_args = build_pytest_args(
        test_files, config,
        json_report=args.json_report,
        extra_args=args.pytest_args,
    )
    rc = run_tests(pytest_args)

    # Summarize if JSON report was generated
    if args.json_report and Path(args.json_report).exists():
        summarize_report(args.json_report)

    sys.exit(rc)


if __name__ == "__main__":
    main()
