#!/usr/bin/env python3
"""Entry script for running transformers tests against candle.

Manages the transformers clone, builds pytest commands, and generates
compatibility reports.

Usage:
    python compat/run.py                           # run all tier1 models
    python compat/run.py --model bert -v           # run bert only, verbose
    python compat/run.py --tier 2                  # run tier1 + tier2
    python compat/run.py --setup-only              # clone transformers only
    python compat/run.py --summarize report.json   # print human-readable report
"""
import argparse
import json
import os
import subprocess
import sys
import textwrap
from pathlib import Path

import yaml

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
COMPAT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = COMPAT_DIR.parent
SRC_DIR = PROJECT_ROOT / "src"
TRANSFORMERS_DIR = COMPAT_DIR / "_transformers"
REPORTS_DIR = COMPAT_DIR / "_reports"


def load_models_config():
    """Load and return the models.yaml configuration."""
    config_path = COMPAT_DIR / "models.yaml"
    with open(config_path) as f:
        return yaml.safe_load(f)


# ---------------------------------------------------------------------------
# Transformers clone management
# ---------------------------------------------------------------------------

def setup_transformers(ref: str):
    """Shallow-clone transformers at the given ref if not already present."""
    if TRANSFORMERS_DIR.exists():
        # Check if already at the right ref
        result = subprocess.run(
            ["git", "-C", str(TRANSFORMERS_DIR), "describe", "--tags", "--exact-match"],
            capture_output=True, text=True,
        )
        if result.returncode == 0 and result.stdout.strip() == ref:
            print(f"[compat] transformers already at {ref}")
            return
        # Wrong ref — re-clone
        print(f"[compat] transformers ref mismatch, re-cloning at {ref}")
        subprocess.run(["rm", "-rf", str(TRANSFORMERS_DIR)], check=True)

    print(f"[compat] cloning transformers at {ref} ...")
    subprocess.run(
        [
            "git", "clone",
            "--depth", "1",
            "--branch", ref,
            "https://github.com/huggingface/transformers.git",
            str(TRANSFORMERS_DIR),
        ],
        check=True,
    )
    # Install transformers from source (editable, no deps — we manage deps)
    subprocess.run(
        [sys.executable, "-m", "pip", "install", "-e",
         str(TRANSFORMERS_DIR), "--no-deps"],
        check=True,
    )
    print(f"[compat] transformers {ref} ready")


# ---------------------------------------------------------------------------
# Bridge conftest generation
# ---------------------------------------------------------------------------

_BRIDGE_CONFTEST = textwrap.dedent("""\
    # Auto-generated by compat/run.py — do not edit
    # This file bridges the transformers test directory to compat/conftest.py
    import sys
    from pathlib import Path

    _compat_dir = Path({compat_dir!r})
    if str(_compat_dir) not in sys.path:
        sys.path.insert(0, str(_compat_dir))

    from conftest import apply_all_patches, pytest_collection_modifyitems  # noqa

    apply_all_patches()
""")


def write_bridge_conftest():
    """Write a conftest.py into the transformers tests/ directory."""
    tests_dir = TRANSFORMERS_DIR / "tests"
    bridge_path = tests_dir / "conftest.py"
    content = _BRIDGE_CONFTEST.format(compat_dir=str(COMPAT_DIR))
    bridge_path.write_text(content)
    return bridge_path


# ---------------------------------------------------------------------------
# Model → test file mapping
# ---------------------------------------------------------------------------

def get_test_files(models: list[str]) -> list[str]:
    """Map model names to transformers test file paths."""
    tests_dir = TRANSFORMERS_DIR / "tests" / "models"
    files = []
    for model in models:
        test_file = tests_dir / model / f"test_modeling_{model}.py"
        if test_file.exists():
            files.append(str(test_file))
        else:
            print(f"[compat] WARNING: test file not found for {model}: {test_file}")
    return files


def get_models_for_tier(config: dict, tier: int) -> list[str]:
    """Return the list of models up to the given tier (inclusive)."""
    models = []
    for t in range(1, tier + 1):
        key = f"tier{t}"
        models.extend(config.get(key, []))
    return models


# ---------------------------------------------------------------------------
# Build pytest command
# ---------------------------------------------------------------------------

def build_pytest_args(
    test_files: list[str],
    config: dict,
    json_report: str | None = None,
    extra_args: list[str] | None = None,
) -> list[str]:
    """Build the full pytest argument list."""
    args = [sys.executable, "-m", "pytest"]

    # Prevent pytest from loading conftest.py files above the tests/ dir
    # (the transformers root conftest imports transformers which triggers
    # dependency version checks before our patches are applied)
    tests_dir = str(TRANSFORMERS_DIR / "tests")
    args.extend(["--confcutdir", tests_dir])

    # Don't abort on collection errors — report them and keep going
    args.append("--continue-on-collection-errors")

    # Build a combined -k expression for deselect patterns
    deselect_parts = []
    for pattern in config.get("deselect_patterns", []):
        deselect_parts.append(_pattern_to_k_expr(pattern))
    if deselect_parts:
        k_expr = " and ".join(f"not ({p})" for p in deselect_parts)
        args.extend(["-k", k_expr])

    # Skip markers via -m
    skip_markers = config.get("skip_markers", [])
    if skip_markers:
        m_expr = " and ".join(f"not {m}" for m in skip_markers)
        args.extend(["-m", m_expr])

    # JSON report
    if json_report:
        args.extend(["--json-report", f"--json-report-file={json_report}"])

    # Test files
    args.extend(test_files)

    # Extra user args (-v, --tb=short, etc.)
    if extra_args:
        args.extend(extra_args)

    return args


def _pattern_to_k_expr(pattern: str) -> str:
    """Convert a glob-like deselect pattern to a pytest -k expression.

    e.g. "*Integration*" → "Integration"
    """
    return pattern.strip("*")


# ---------------------------------------------------------------------------
# Run tests
# ---------------------------------------------------------------------------

def run_tests(pytest_args: list[str]) -> int:
    """Run pytest as a subprocess with USE_CANDLE=1."""
    env = os.environ.copy()
    env["USE_CANDLE"] = "1"
    # Ensure candle src is on PYTHONPATH
    pythonpath = env.get("PYTHONPATH", "")
    paths = [str(SRC_DIR)]
    if pythonpath:
        paths.append(pythonpath)
    env["PYTHONPATH"] = os.pathsep.join(paths)

    print(f"[compat] running: {' '.join(pytest_args)}")
    result = subprocess.run(pytest_args, env=env)
    return result.returncode


# ---------------------------------------------------------------------------
# Report summarization
# ---------------------------------------------------------------------------

def summarize_report(report_path: str):
    """Print a human-readable summary from a pytest-json-report file."""
    with open(report_path) as f:
        report = json.load(f)

    tests = report.get("tests", [])
    collectors = report.get("collectors", [])

    # Count collection errors
    collection_errors = []
    for c in collectors:
        if c.get("outcome") == "failed":
            nodeid = c.get("nodeid", "")
            longrepr = c.get("longrepr", "")
            collection_errors.append((nodeid, longrepr))

    if not tests and not collection_errors:
        print("[compat] no test results found in report")
        return

    # Group by model
    model_stats: dict[str, dict] = {}
    for test in tests:
        nodeid = test.get("nodeid", "")
        outcome = test.get("outcome", "unknown")

        # Extract model name from nodeid
        model = _extract_model_name(nodeid)

        if model not in model_stats:
            model_stats[model] = {
                "total": 0, "passed": 0, "failed": 0,
                "xfailed": 0, "xpassed": 0, "skipped": 0,
            }
        stats = model_stats[model]
        stats["total"] += 1
        if outcome == "passed":
            stats["passed"] += 1
        elif outcome == "failed":
            stats["failed"] += 1
        elif outcome == "xfailed":
            stats["xfailed"] += 1
        elif outcome == "xpassed":
            stats["xpassed"] += 1
        elif outcome == "skipped":
            stats["skipped"] += 1

    # Import candle version
    try:
        sys.path.insert(0, str(SRC_DIR))
        import candle
        candle_version = candle.__version__
    except ImportError:
        candle_version = "unknown"

    config = load_models_config()
    tf_ref = config.get("transformers_ref", "unknown")

    # Print summary table
    print()
    print("=== Candle x Transformers Compatibility ===")
    print(f"Transformers: {tf_ref} | Candle: {candle_version}")
    print()

    header = f"{'Model':<14} {'Total':>5} {'Pass':>5} {'Fail':>5} {'XFail':>5} {'XPass':>5} {'Skip':>5} {'Pass%':>6}"
    print(header)
    print("-" * len(header))

    totals = {"total": 0, "passed": 0, "failed": 0, "xfailed": 0, "xpassed": 0, "skipped": 0}

    for model in sorted(model_stats):
        s = model_stats[model]
        pass_pct = (s["passed"] / s["total"] * 100) if s["total"] > 0 else 0
        print(
            f"{model:<14} {s['total']:>5} {s['passed']:>5} {s['failed']:>5} "
            f"{s['xfailed']:>5} {s['xpassed']:>5} {s['skipped']:>5} {pass_pct:>5.1f}%"
        )
        for k in totals:
            totals[k] += s[k]

    print("-" * len(header))
    total_pct = (totals["passed"] / totals["total"] * 100) if totals["total"] > 0 else 0
    print(
        f"{'TOTAL':<14} {totals['total']:>5} {totals['passed']:>5} {totals['failed']:>5} "
        f"{totals['xfailed']:>5} {totals['xpassed']:>5} {totals['skipped']:>5} {total_pct:>5.1f}%"
    )
    print()

    if collection_errors:
        print(f"Collection errors: {len(collection_errors)}")
        for nodeid, longrepr in collection_errors:
            # Show first line of the error
            first_line = longrepr.split("\n")[-1] if longrepr else "unknown"
            print(f"  COLLECT ERROR  {nodeid}")
            print(f"                 {first_line}")
        print()


def _extract_model_name(nodeid: str) -> str:
    """Extract model name from a pytest nodeid like tests/models/bert/test_modeling_bert.py::..."""
    parts = nodeid.split("/")
    for i, part in enumerate(parts):
        if part == "models" and i + 1 < len(parts):
            return parts[i + 1]
    # fallback: use the filename
    filename = nodeid.split("::")[0].split("/")[-1]
    if filename.startswith("test_modeling_"):
        return filename.replace("test_modeling_", "").replace(".py", "")
    return "unknown"


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Run transformers compatibility tests against candle",
    )
    parser.add_argument(
        "--model", type=str, default=None,
        help="Run tests for a single model (e.g., bert, gpt2)",
    )
    parser.add_argument(
        "--tier", type=int, default=1,
        help="Run models up to this tier (default: 1)",
    )
    parser.add_argument(
        "--setup-only", action="store_true",
        help="Only clone/setup transformers, don't run tests",
    )
    parser.add_argument(
        "--json-report", type=str, default=None,
        help="Path to write pytest-json-report output",
    )
    parser.add_argument(
        "--summarize", type=str, default=None,
        help="Summarize a previous JSON report file and exit",
    )
    parser.add_argument(
        "--transformers-ref", type=str, default=None,
        help="Override the transformers git ref (default: from models.yaml)",
    )

    args, extra = parser.parse_known_args()
    # Everything not consumed by our parser is forwarded to pytest
    args.pytest_args = extra

    # Summarize mode: just print and exit
    if args.summarize:
        summarize_report(args.summarize)
        return

    config = load_models_config()
    ref = args.transformers_ref or config.get("transformers_ref", "v4.47.0")

    # Clone / setup
    setup_transformers(ref)

    if args.setup_only:
        print("[compat] setup complete")
        return

    # Write bridge conftest
    write_bridge_conftest()

    # Determine which models to test
    if args.model:
        models = [args.model]
    else:
        models = get_models_for_tier(config, args.tier)

    if not models:
        print("[compat] no models selected")
        return

    print(f"[compat] testing models: {', '.join(models)}")

    # Map to test files
    test_files = get_test_files(models)
    if not test_files:
        print("[compat] no test files found")
        sys.exit(1)

    # Ensure reports directory exists for json output
    if args.json_report:
        report_path = Path(args.json_report)
        report_path.parent.mkdir(parents=True, exist_ok=True)

    # Build and run pytest
    pytest_args = build_pytest_args(
        test_files, config,
        json_report=args.json_report,
        extra_args=args.pytest_args,
    )
    rc = run_tests(pytest_args)

    # Summarize if JSON report was generated
    if args.json_report and Path(args.json_report).exists():
        summarize_report(args.json_report)

    sys.exit(rc)


if __name__ == "__main__":
    main()
