"""Auto-generated backward Node classes — DO NOT EDIT.

Generated by tools/autograd/gen_functions.py from derivatives.yaml.
"""
from __future__ import annotations

import math as _math

from ..autograd.node import Node
from .._backends.autograd import (
    _grad_context,
    _strip_autograd_keys,
    _backward_dispatch_keyset,
    _scalar_tensor_like,
)
from .._dispatch.dispatcher import redispatch
from ..autograd.utils import reduce_grad


def _inverse_permutation(dims):
    inv = [0] * len(dims)
    for i, d in enumerate(dims):
        inv[d] = i
    return inv


# ---------------------------------------------------------------------------
# Activation backward helpers (called from generated formulas)
# ---------------------------------------------------------------------------

def _silu_grad(grad, self_, keyset):
    sig = redispatch("sigmoid", keyset, self_)
    ones = self_._ones_like()
    one_minus_sig = redispatch("add", keyset, ones, redispatch("neg", keyset, sig))
    x_mul = redispatch("mul", keyset, self_, one_minus_sig)
    factor = redispatch("mul", keyset, sig, redispatch("add", keyset, ones, x_mul))
    return redispatch("mul", keyset, grad, factor)


def _gelu_grad(grad, self_, keyset):
    sqrt2 = _scalar_tensor_like(self_, _math.sqrt(2.0))
    x_over_sqrt2 = redispatch("div", keyset, self_, sqrt2)
    erf_val = redispatch("erf", keyset, x_over_sqrt2)
    ones = self_._ones_like()
    half = _scalar_tensor_like(self_, 0.5)
    cdf = redispatch("mul", keyset, half, redispatch("add", keyset, ones, erf_val))
    coeff = _scalar_tensor_like(self_, 1.0 / _math.sqrt(2.0 * _math.pi))
    x_sq = redispatch("mul", keyset, self_, self_)
    neg_half_x_sq = redispatch("mul", keyset, _scalar_tensor_like(self_, -0.5), x_sq)
    pdf = redispatch("mul", keyset, coeff, redispatch("exp", keyset, neg_half_x_sq))
    x_pdf = redispatch("mul", keyset, self_, pdf)
    factor = redispatch("add", keyset, cdf, x_pdf)
    return redispatch("mul", keyset, grad, factor)


def _mish_grad(grad, self_, keyset):
    ones = self_._ones_like()
    sp = redispatch("softplus", keyset, self_)
    tanh_sp = redispatch("tanh", keyset, sp)
    tanh_sp_sq = redispatch("mul", keyset, tanh_sp, tanh_sp)
    sech2 = redispatch("add", keyset, ones, redispatch("neg", keyset, tanh_sp_sq))
    sig = redispatch("sigmoid", keyset, self_)
    tail = redispatch("mul", keyset, self_, redispatch("mul", keyset, sech2, sig))
    factor = redispatch("add", keyset, tanh_sp, tail)
    return redispatch("mul", keyset, grad, factor)


def _leaky_relu_grad(grad, self_, negative_slope, keyset):
    pos_mask = redispatch("sign", keyset, redispatch("relu", keyset, self_))
    ones = self_._ones_like()
    nonpos_mask = redispatch("add", keyset, ones, redispatch("neg", keyset, pos_mask))
    slope = _scalar_tensor_like(self_, negative_slope)
    factor = redispatch("add", keyset, pos_mask, redispatch("mul", keyset, nonpos_mask, slope))
    return redispatch("mul", keyset, grad, factor)


def _elu_grad(grad, self_, alpha, keyset):
    pos_mask = redispatch("sign", keyset, redispatch("relu", keyset, self_))
    ones = self_._ones_like()
    nonpos_mask = redispatch("add", keyset, ones, redispatch("neg", keyset, pos_mask))
    alpha_t = _scalar_tensor_like(self_, float(alpha))
    exp_x = redispatch("exp", keyset, self_)
    neg_branch = redispatch("mul", keyset, alpha_t, exp_x)
    factor = redispatch("add", keyset, pos_mask, redispatch("mul", keyset, nonpos_mask, neg_branch))
    return redispatch("mul", keyset, grad, factor)


def _celu_grad(grad, self_, alpha, keyset):
    alpha_t = _scalar_tensor_like(self_, float(alpha))
    small_eps = _scalar_tensor_like(self_, 1e-7)
    ones = self_._ones_like()
    pos_mask = redispatch("sign", keyset, redispatch("relu", keyset,
        redispatch("add", keyset, self_, small_eps)))
    neg_mask = redispatch("add", keyset, ones, redispatch("neg", keyset, pos_mask))
    exp_x_alpha = redispatch("exp", keyset, redispatch("div", keyset, self_, alpha_t))
    deriv = redispatch("add", keyset, pos_mask, redispatch("mul", keyset, neg_mask, exp_x_alpha))
    return redispatch("mul", keyset, grad, deriv)


def _hardtanh_grad(grad, self_, min_val, max_val, keyset):
    min_t = _scalar_tensor_like(self_, float(min_val))
    max_t = _scalar_tensor_like(self_, float(max_val))
    ge_min = redispatch("ge", keyset, self_, min_t)
    le_max = redispatch("le", keyset, self_, max_t)
    mask = redispatch("mul", keyset,
        redispatch("where", keyset, ge_min, self_._ones_like(), _scalar_tensor_like(self_, 0.0)),
        redispatch("where", keyset, le_max, self_._ones_like(), _scalar_tensor_like(self_, 0.0)))
    return redispatch("mul", keyset, grad, mask)


def _hardswish_grad(grad, self_, keyset):
    three = _scalar_tensor_like(self_, 3.0)
    sixth = _scalar_tensor_like(self_, 1.0 / 6.0)
    two = _scalar_tensor_like(self_, 2.0)
    ones = self_._ones_like()
    zero = _scalar_tensor_like(self_, 0.0)
    gt_neg3 = redispatch("gt", keyset, self_, redispatch("neg", keyset, three))
    lt_3 = redispatch("lt", keyset, self_, three)
    inner_mask = redispatch("mul", keyset,
        redispatch("where", keyset, gt_neg3, ones, zero),
        redispatch("where", keyset, lt_3, ones, zero))
    ge_3_mask = redispatch("where", keyset, redispatch("ge", keyset, self_, three), ones, zero)
    two_x_plus_3 = redispatch("add", keyset, redispatch("mul", keyset, two, self_), three)
    inner_grad = redispatch("mul", keyset, two_x_plus_3, sixth)
    dout = redispatch("add", keyset,
        redispatch("mul", keyset, inner_grad, inner_mask), ge_3_mask)
    return redispatch("mul", keyset, grad, dout)


def _hardsigmoid_grad(grad, self_, keyset):
    three = _scalar_tensor_like(self_, 3.0)
    sixth = _scalar_tensor_like(self_, 1.0 / 6.0)
    ones = self_._ones_like()
    zero = _scalar_tensor_like(self_, 0.0)
    gt_neg3 = redispatch("gt", keyset, self_, redispatch("neg", keyset, three))
    lt_3 = redispatch("lt", keyset, self_, three)
    inner_mask = redispatch("mul", keyset,
        redispatch("where", keyset, gt_neg3, ones, zero),
        redispatch("where", keyset, lt_3, ones, zero))
    return redispatch("mul", keyset, grad, redispatch("mul", keyset, inner_mask, sixth))


def _selu_grad(grad, self_, keyset):
    SCALE = 1.0507009873554804934193349852946
    ALPHA = 1.6732631921893986195596513061800
    scale_t = _scalar_tensor_like(self_, SCALE)
    alpha_scale_t = _scalar_tensor_like(self_, SCALE * ALPHA)
    small_eps = _scalar_tensor_like(self_, 1e-7)
    ones = self_._ones_like()
    pos_mask = redispatch("sign", keyset, redispatch("relu", keyset,
        redispatch("add", keyset, self_, small_eps)))
    neg_mask = redispatch("add", keyset, ones, redispatch("neg", keyset, pos_mask))
    exp_x = redispatch("exp", keyset, self_)
    neg_deriv = redispatch("mul", keyset, alpha_scale_t, exp_x)
    deriv = redispatch("add", keyset,
        redispatch("mul", keyset, pos_mask, scale_t),
        redispatch("mul", keyset, neg_mask, neg_deriv))
    return redispatch("mul", keyset, grad, deriv)


def _softmax_grad(grad, self_, dim, keyset):
    s = redispatch("softmax", keyset, self_, dim)
    gs = redispatch("mul", keyset, grad, s)
    gs_sum = redispatch("sum", keyset, gs, dim=dim, keepdim=True)
    return redispatch("mul", keyset, s, redispatch("add", keyset, grad,
        redispatch("neg", keyset, gs_sum)))


def _log_softmax_grad(grad, self_, dim, keyset):
    log_s = redispatch("log_softmax", keyset, self_, dim)
    s = redispatch("exp", keyset, log_s)
    grad_sum = redispatch("sum", keyset, grad, dim=dim, keepdim=True)
    return redispatch("add", keyset, grad,
        redispatch("neg", keyset, redispatch("mul", keyset, s, grad_sum)))


def _prelu_grad_input(grad, self_, weight, keyset):
    pos_mask = redispatch("sign", keyset, redispatch("relu", keyset, self_))
    ones = self_._ones_like()
    nonpos_mask = redispatch("add", keyset, ones, redispatch("neg", keyset, pos_mask))
    factor = redispatch("add", keyset, pos_mask, redispatch("mul", keyset, nonpos_mask, weight))
    return redispatch("mul", keyset, grad, factor)


def _prelu_grad_weight(grad, self_, weight, keyset):
    pos_mask = redispatch("sign", keyset, redispatch("relu", keyset, self_))
    ones = self_._ones_like()
    nonpos_mask = redispatch("add", keyset, ones, redispatch("neg", keyset, pos_mask))
    w_input = redispatch("mul", keyset, nonpos_mask, self_)
    return redispatch("mul", keyset, grad, w_input)


# ---------------------------------------------------------------------------
# Norm backward helpers (called from generated formulas)
# ---------------------------------------------------------------------------

def _norm_stats(x, axes, eps, keyset):
    """Shared: compute mean, diff, inv_std, x_hat for norm backward."""
    mean = redispatch("mean", keyset, x, dim=axes, keepdim=True)
    diff = redispatch("add", keyset, x, redispatch("neg", keyset, mean))
    var = redispatch("mean", keyset, redispatch("mul", keyset, diff, diff), dim=axes, keepdim=True)
    eps_t = _scalar_tensor_like(x, eps)
    inv_std = redispatch("rsqrt", keyset, redispatch("add", keyset, var, eps_t))
    x_hat = redispatch("mul", keyset, diff, inv_std)
    return inv_std, x_hat


def _norm_grad_core(dl_dxhat, x_hat, inv_std, axes, n, keyset):
    """Shared: compute grad_input from dl_dxhat, x_hat, inv_std."""
    n_t = _scalar_tensor_like(x_hat, float(n))
    mean_dl = redispatch("div", keyset,
        redispatch("sum", keyset, dl_dxhat, dim=axes, keepdim=True), n_t)
    mean_dl_xhat = redispatch("div", keyset,
        redispatch("sum", keyset, redispatch("mul", keyset, dl_dxhat, x_hat),
                   dim=axes, keepdim=True), n_t)
    return redispatch("mul", keyset, inv_std,
        redispatch("add", keyset,
            redispatch("add", keyset, dl_dxhat, redispatch("neg", keyset, mean_dl)),
            redispatch("neg", keyset, redispatch("mul", keyset, x_hat, mean_dl_xhat))))


def _layer_norm_grad_input(grad, input_, normalized_shape, weight, eps, keyset):
    norm_shape = tuple(normalized_shape)
    ndim = len(input_.shape)
    n_norm = len(norm_shape)
    axes = tuple(range(ndim - n_norm, ndim))
    inv_std, x_hat = _norm_stats(input_, axes, eps, keyset)
    dl_dxhat = redispatch("mul", keyset, grad, weight) if weight is not None else grad
    n = 1
    for d in axes:
        n *= input_.shape[d]
    return _norm_grad_core(dl_dxhat, x_hat, inv_std, axes, n, keyset)


def _batch_norm_grad_input(grad, input_, weight, eps, keyset):
    ndim = len(input_.shape)
    axes = (0,) + tuple(range(2, ndim))
    shape_for_stats = [1, input_.shape[1]] + [1] * (ndim - 2)
    inv_std, x_hat = _norm_stats(input_, axes, eps, keyset)
    if weight is not None:
        dl_dxhat = redispatch("mul", keyset, grad, weight.reshape(shape_for_stats))
    else:
        dl_dxhat = grad
    n = 1
    for ax in axes:
        n *= input_.shape[ax]
    return _norm_grad_core(dl_dxhat, x_hat, inv_std, axes, n, keyset)


def _group_norm_grad_input(grad, input_, num_groups, weight, eps, keyset):
    N = input_.shape[0]
    C = input_.shape[1]
    spatial = input_.shape[2:]
    channels_per_group = C // num_groups
    group_size = channels_per_group
    for s in spatial:
        group_size *= s
    reshaped = redispatch("reshape", keyset, input_,
                          (N, num_groups, channels_per_group, *spatial))
    axes = tuple(range(2, len(reshaped.shape)))
    inv_std, x_hat = _norm_stats(reshaped, axes, eps, keyset)
    grad_reshaped = redispatch("reshape", keyset, grad,
                               (N, num_groups, channels_per_group, *spatial))
    if weight is not None:
        w_shape = [1, num_groups, channels_per_group] + [1] * len(spatial)
        w_reshaped = redispatch("reshape", keyset, weight, tuple(w_shape))
        dl_dxhat = redispatch("mul", keyset, grad_reshaped, w_reshaped)
    else:
        dl_dxhat = grad_reshaped
    grad_out = _norm_grad_core(dl_dxhat, x_hat, inv_std, axes, group_size, keyset)
    return redispatch("reshape", keyset, grad_out, input_.shape)


def _rms_norm_grad_input(grad, input_, normalized_shape, weight, eps, keyset):
    norm_shape = tuple(normalized_shape)
    ndim = len(input_.shape)
    n_norm = len(norm_shape)
    axes = tuple(range(ndim - n_norm, ndim))
    x_sq = redispatch("mul", keyset, input_, input_)
    variance = redispatch("mean", keyset, x_sq, dim=axes, keepdim=True)
    eps_t = _scalar_tensor_like(input_, eps)
    rms = redispatch("sqrt", keyset, redispatch("add", keyset, variance, eps_t))
    x_hat = redispatch("div", keyset, input_, rms)
    dl_dxhat = redispatch("mul", keyset, grad, weight) if weight is not None else grad
    n = 1
    for d in axes:
        n *= input_.shape[d]
    n_t = _scalar_tensor_like(input_, float(n))
    dot = redispatch("sum", keyset,
        redispatch("mul", keyset, dl_dxhat, x_hat), dim=axes, keepdim=True)
    return redispatch("div", keyset,
        redispatch("add", keyset, dl_dxhat,
            redispatch("neg", keyset, redispatch("mul", keyset, x_hat,
                redispatch("div", keyset, dot, n_t)))),
        rms)


# ---------------------------------------------------------------------------
# Conv backward helpers (Phase 2)
# ---------------------------------------------------------------------------

class _ConvGradCache:
    """Cache conv backward results to avoid recomputation across grad formulas."""
    _cache = {}

    @classmethod
    def get(cls, key, compute_fn):
        if key not in cls._cache:
            cls._cache[key] = compute_fn()
        return cls._cache[key]

    @classmethod
    def clear(cls):
        cls._cache.clear()


def _conv_backward_all(grad, input_, weight, bias, stride, padding, dilation, groups, name, keyset):
    """Compute all conv gradients, returning (grad_input, grad_weight, grad_bias).

    Delegates to the existing _conv_backward implementation.
    Always returns a 3-tuple (grad_bias is None when bias is None).
    """
    from .._backends.autograd import _conv_backward
    args = (stride, padding, dilation, groups)
    result = _conv_backward(name, grad, input_, weight, bias,
                            input_, weight, bias, keyset, args, {})
    if len(result) == 2:
        return result[0], result[1], None
    return result


# ---------------------------------------------------------------------------
# Pool backward helpers (Phase 2)
# ---------------------------------------------------------------------------

def _max_pool1d_backward_helper(grad, self_, result, kernel_size, stride, padding, dilation, ceil_mode, keyset):
    from .._backends.autograd import _max_pool1d_backward
    args = (kernel_size, stride, padding, dilation, ceil_mode)
    return _max_pool1d_backward(grad, self_, self_, result, keyset, args, {})[0]


def _max_pool2d_backward_helper(grad, self_, result, kernel_size, stride, padding, dilation, ceil_mode, keyset):
    from .._backends.autograd import _max_pool2d_backward
    args = (kernel_size, stride, padding, dilation, ceil_mode)
    return _max_pool2d_backward(grad, self_, self_, result, keyset, args, {})[0]


def _max_pool3d_backward_helper(grad, self_, result, kernel_size, stride, padding, dilation, ceil_mode, keyset):
    from .._backends.autograd import _max_pool3d_backward
    args = (kernel_size, stride, padding, dilation, ceil_mode)
    return _max_pool3d_backward(grad, self_, self_, result, keyset, args, {})[0]


def _avg_pool1d_backward_helper(grad, self_, kernel_size, stride, padding, ceil_mode, count_include_pad, keyset):
    from .._backends.autograd import _avg_pool1d_backward
    args = (kernel_size, stride, padding, ceil_mode, count_include_pad)
    return _avg_pool1d_backward(grad, self_, self_, None, keyset, args, {})[0]


def _avg_pool2d_backward_helper(grad, self_, kernel_size, stride, padding, ceil_mode, count_include_pad, keyset):
    from .._backends.autograd import _avg_pool2d_backward
    args = (kernel_size, stride, padding, ceil_mode, count_include_pad)
    return _avg_pool2d_backward(grad, self_, self_, None, keyset, args, {})[0]


def _avg_pool3d_backward_helper(grad, self_, kernel_size, stride, padding, ceil_mode, count_include_pad, keyset):
    from .._backends.autograd import _avg_pool3d_backward
    args = (kernel_size, stride, padding, ceil_mode, count_include_pad)
    return _avg_pool3d_backward(grad, self_, self_, None, keyset, args, {})[0]


def _adaptive_avg_pool1d_backward_helper(grad, self_, output_size, keyset):
    from .._backends.autograd import _adaptive_avg_pool1d_backward
    args = (output_size,)
    return _adaptive_avg_pool1d_backward(grad, self_, self_, None, keyset, args, {})[0]


def _adaptive_avg_pool2d_backward_helper(grad, self_, output_size, keyset):
    from .._backends.autograd import _adaptive_avg_pool2d_backward
    args = (output_size,)
    return _adaptive_avg_pool2d_backward(grad, self_, self_, None, keyset, args, {})[0]


def _adaptive_avg_pool3d_backward_helper(grad, self_, output_size, keyset):
    from .._backends.autograd import _adaptive_avg_pool3d_backward
    args = (output_size,)
    return _adaptive_avg_pool3d_backward(grad, self_, self_, None, keyset, args, {})[0]


def _adaptive_max_pool1d_backward_helper(grad, self_, result, output_size, keyset):
    from .._backends.autograd import _adaptive_max_pool1d_backward
    args = (output_size,)
    return _adaptive_max_pool1d_backward(grad, self_, self_, result, keyset, args, {})[0]


def _adaptive_max_pool2d_backward_helper(grad, self_, result, output_size, keyset):
    from .._backends.autograd import _adaptive_max_pool2d_backward
    args = (output_size,)
    return _adaptive_max_pool2d_backward(grad, self_, self_, result, keyset, args, {})[0]


# ---------------------------------------------------------------------------
# Upsample backward helpers (Phase 2)
# ---------------------------------------------------------------------------

def _upsample_nearest1d_backward_helper(grad, self_, output_size, keyset):
    from .._backends.autograd import _upsample_nearest1d_backward
    args = (output_size,)
    return _upsample_nearest1d_backward(grad, self_, self_, None, keyset, args, {})[0]


def _upsample_nearest2d_backward_helper(grad, self_, output_size, keyset):
    from .._backends.autograd import _upsample_nearest2d_backward
    args = (output_size,)
    return _upsample_nearest2d_backward(grad, self_, self_, None, keyset, args, {})[0]


def _upsample_bilinear2d_backward_helper(grad, self_, output_size, align_corners, keyset):
    from .._backends.autograd import _upsample_bilinear2d_backward
    args = (output_size, align_corners)
    return _upsample_bilinear2d_backward(grad, self_, self_, None, keyset, args, {})[0]


def _upsample_linear1d_backward_helper(grad, self_, output_size, align_corners, keyset):
    from .._backends.autograd import _upsample_linear1d_backward
    args = (output_size, align_corners)
    return _upsample_linear1d_backward(grad, self_, self_, None, keyset, args, {})[0]


def _upsample_bicubic2d_backward_helper(grad, self_, output_size, align_corners, keyset):
    from .._backends.autograd import _upsample_bicubic2d_backward
    args = (output_size, align_corners)
    return _upsample_bicubic2d_backward(grad, self_, self_, None, keyset, args, {})[0]


class ExpBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='ExpBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_result_idx = None

    def _save(self, *, result=None):
        tensors = []
        if result is not None:
            self._saved_result_idx = len(tensors)
            tensors.append(result)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        result = _saved[self._saved_result_idx]
        with _grad_context(keyset):
            grad_self = redispatch("mul", keyset, grad, result)
        return (grad_self,)

class LogBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='LogBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = redispatch("div", keyset, grad, self_)
        return (grad_self,)

class SqrtBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='SqrtBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = redispatch("div", keyset, grad, redispatch("mul", keyset, _scalar_tensor_like(self_, 2.0), redispatch("sqrt", keyset, self_)))
        return (grad_self,)

class RsqrtBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='RsqrtBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = redispatch("mul", keyset, grad, redispatch("mul", keyset, _scalar_tensor_like(self_, -0.5), redispatch("mul", keyset, redispatch("rsqrt", keyset, self_), redispatch("mul", keyset, redispatch("rsqrt", keyset, self_), redispatch("rsqrt", keyset, self_)))))
        return (grad_self,)

class NegBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='NegBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        with _grad_context(keyset):
            grad_self = redispatch("neg", keyset, grad)
        return (grad_self,)

class AbsBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='AbsBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = redispatch("mul", keyset, grad, redispatch("sign", keyset, self_))
        return (grad_self,)

class SigmoidBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='SigmoidBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = redispatch("mul", keyset, grad, redispatch("mul", keyset, redispatch("sigmoid", keyset, self_), redispatch("add", keyset, self_._ones_like(), redispatch("neg", keyset, redispatch("sigmoid", keyset, self_)))))
        return (grad_self,)

class TanhBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='TanhBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = redispatch("mul", keyset, grad, redispatch("add", keyset, self_._ones_like(), redispatch("neg", keyset, redispatch("mul", keyset, redispatch("tanh", keyset, self_), redispatch("tanh", keyset, self_)))))
        return (grad_self,)

class SinBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='SinBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = redispatch("mul", keyset, grad, redispatch("cos", keyset, self_))
        return (grad_self,)

class CosBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='CosBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = redispatch("mul", keyset, grad, redispatch("neg", keyset, redispatch("sin", keyset, self_)))
        return (grad_self,)

class ReluBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='ReluBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = redispatch("mul", keyset, grad, redispatch("sign", keyset, redispatch("relu", keyset, self_)))
        return (grad_self,)

class AddBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='AddBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._saved_other_idx = None

    def _save(self, *, self_=None, other=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if other is not None:
            self._saved_other_idx = len(tensors)
            tensors.append(other)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        other = _saved[self._saved_other_idx]
        with _grad_context(keyset):
            grad_self = reduce_grad(grad, self_.shape)
            grad_other = reduce_grad(grad, other.shape)
        return (grad_self, grad_other,)

class MulBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='MulBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_other_idx = None
        self._saved_self_idx = None

    def _save(self, *, other=None, self_=None):
        tensors = []
        if other is not None:
            self._saved_other_idx = len(tensors)
            tensors.append(other)
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        other = _saved[self._saved_other_idx]
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = reduce_grad(redispatch("mul", keyset, grad, other), self_.shape)
            grad_other = reduce_grad(redispatch("mul", keyset, grad, self_), other.shape)
        return (grad_self, grad_other,)

class SubBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='SubBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._saved_other_idx = None

    def _save(self, *, self_=None, other=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if other is not None:
            self._saved_other_idx = len(tensors)
            tensors.append(other)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        other = _saved[self._saved_other_idx]
        with _grad_context(keyset):
            grad_self = reduce_grad(grad, self_.shape)
            grad_other = reduce_grad(redispatch("neg", keyset, grad), other.shape)
        return (grad_self, grad_other,)

class DivBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='DivBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_other_idx = None
        self._saved_self_idx = None

    def _save(self, *, other=None, self_=None):
        tensors = []
        if other is not None:
            self._saved_other_idx = len(tensors)
            tensors.append(other)
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        other = _saved[self._saved_other_idx]
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = reduce_grad(redispatch("div", keyset, grad, other), self_.shape)
            grad_other = reduce_grad(redispatch("neg", keyset, redispatch("div", keyset, redispatch("mul", keyset, grad, self_), redispatch("mul", keyset, other, other))), other.shape)
        return (grad_self, grad_other,)

class MatmulBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='MatmulBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_other_idx = None
        self._saved_self_idx = None

    def _save(self, *, other=None, self_=None):
        tensors = []
        if other is not None:
            self._saved_other_idx = len(tensors)
            tensors.append(other)
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        other = _saved[self._saved_other_idx]
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = reduce_grad(redispatch("matmul", keyset, grad, other.transpose(-1, -2)), self_.shape)
            grad_other = reduce_grad(redispatch("matmul", keyset, self_.transpose(-1, -2), grad), other.shape)
        return (grad_self, grad_other,)

class ReshapeBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='ReshapeBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._shape = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        shape = self._shape
        with _grad_context(keyset):
            grad_self = redispatch("reshape", keyset, grad, self_.shape)
        return (grad_self,)

class TransposeBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='TransposeBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._dim0 = None
        self._dim1 = None

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        dim0 = self._dim0
        dim1 = self._dim1
        with _grad_context(keyset):
            grad_self = redispatch("transpose", keyset, grad, dim0, dim1)
        return (grad_self,)

class PermuteBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='PermuteBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._dims = None

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        dims = self._dims
        with _grad_context(keyset):
            grad_self = redispatch("permute", keyset, grad, _inverse_permutation(dims))
        return (grad_self,)

class ExpandBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='ExpandBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._size = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        size = self._size
        with _grad_context(keyset):
            grad_self = reduce_grad(grad, self_.shape)
        return (grad_self,)

class SqueezeBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='SqueezeBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = redispatch("reshape", keyset, grad, self_.shape)
        return (grad_self,)

class UnsqueezeBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='UnsqueezeBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._dim = None

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        dim = self._dim
        with _grad_context(keyset):
            grad_self = redispatch("squeeze", keyset, grad, dim)
        return (grad_self,)

class SumBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='SumBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = redispatch("mul", keyset, grad, self_._ones_like())
        return (grad_self,)

class MeanBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='MeanBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = redispatch("mul", keyset, redispatch("mul", keyset, grad, _scalar_tensor_like(self_, 1.0 / self_.numel())), self_._ones_like())
        return (grad_self,)

class ContiguousBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='ContiguousBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        with _grad_context(keyset):
            grad_self = grad
        return (grad_self,)

class ErfBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='ErfBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = redispatch("mul", keyset, grad, redispatch("mul", keyset, _scalar_tensor_like(self_, 2.0 / __import__('math').sqrt(__import__('math').pi)), redispatch("exp", keyset, redispatch("neg", keyset, redispatch("mul", keyset, self_, self_)))))
        return (grad_self,)

class SoftplusBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='SoftplusBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = redispatch("mul", keyset, grad, redispatch("sigmoid", keyset, self_))
        return (grad_self,)

class SiluBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='SiluBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = _silu_grad(grad, self_, keyset)
        return (grad_self,)

class GeluBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='GeluBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = _gelu_grad(grad, self_, keyset)
        return (grad_self,)

class MishBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='MishBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = _mish_grad(grad, self_, keyset)
        return (grad_self,)

class Leaky_reluBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Leaky_reluBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._negative_slope = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        negative_slope = self._negative_slope
        with _grad_context(keyset):
            grad_self = _leaky_relu_grad(grad, self_, negative_slope, keyset)
        return (grad_self,)

class EluBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='EluBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._alpha = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        alpha = self._alpha
        with _grad_context(keyset):
            grad_self = _elu_grad(grad, self_, alpha, keyset)
        return (grad_self,)

class CeluBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='CeluBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._alpha = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        alpha = self._alpha
        with _grad_context(keyset):
            grad_self = _celu_grad(grad, self_, alpha, keyset)
        return (grad_self,)

class HardtanhBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='HardtanhBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._min_val = None
        self._max_val = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        min_val = self._min_val
        max_val = self._max_val
        with _grad_context(keyset):
            grad_self = _hardtanh_grad(grad, self_, min_val, max_val, keyset)
        return (grad_self,)

class Relu6Backward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Relu6Backward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = _hardtanh_grad(grad, self_, 0.0, 6.0, keyset)
        return (grad_self,)

class HardswishBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='HardswishBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = _hardswish_grad(grad, self_, keyset)
        return (grad_self,)

class HardsigmoidBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='HardsigmoidBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = _hardsigmoid_grad(grad, self_, keyset)
        return (grad_self,)

class SeluBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='SeluBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        with _grad_context(keyset):
            grad_self = _selu_grad(grad, self_, keyset)
        return (grad_self,)

class SoftmaxBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='SoftmaxBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._dim = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        dim = self._dim
        with _grad_context(keyset):
            grad_self = _softmax_grad(grad, self_, dim, keyset)
        return (grad_self,)

class Log_softmaxBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Log_softmaxBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._dim = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        dim = self._dim
        with _grad_context(keyset):
            grad_self = _log_softmax_grad(grad, self_, dim, keyset)
        return (grad_self,)

class PreluBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='PreluBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._saved_weight_idx = None

    def _save(self, *, self_=None, weight=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if weight is not None:
            self._saved_weight_idx = len(tensors)
            tensors.append(weight)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        weight = _saved[self._saved_weight_idx]
        with _grad_context(keyset):
            grad_self = _prelu_grad_input(grad, self_, weight, keyset)
            grad_weight = reduce_grad(_prelu_grad_weight(grad, self_, weight, keyset), weight.shape)
        return (grad_self, grad_weight,)

class Layer_normBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Layer_normBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_input_idx = None
        self._saved_weight_idx = None
        self._normalized_shape = None
        self._eps = None

    def _save(self, *, input_=None, weight=None):
        tensors = []
        if input_ is not None:
            self._saved_input_idx = len(tensors)
            tensors.append(input_)
        if weight is not None:
            self._saved_weight_idx = len(tensors)
            tensors.append(weight)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        input_ = _saved[self._saved_input_idx]
        weight = _saved[self._saved_weight_idx] if self._saved_weight_idx is not None else None
        normalized_shape = self._normalized_shape
        eps = self._eps
        with _grad_context(keyset):
            grad_input = _layer_norm_grad_input(grad, input_, normalized_shape, weight, eps, keyset)
        return (grad_input, None, None,)

class Batch_normBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Batch_normBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_input_idx = None
        self._saved_weight_idx = None
        self._training = None
        self._momentum = None
        self._eps = None

    def _save(self, *, input_=None, weight=None):
        tensors = []
        if input_ is not None:
            self._saved_input_idx = len(tensors)
            tensors.append(input_)
        if weight is not None:
            self._saved_weight_idx = len(tensors)
            tensors.append(weight)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        input_ = _saved[self._saved_input_idx]
        weight = _saved[self._saved_weight_idx] if self._saved_weight_idx is not None else None
        training = self._training
        momentum = self._momentum
        eps = self._eps
        with _grad_context(keyset):
            grad_input = _batch_norm_grad_input(grad, input_, weight, eps, keyset)
        return (grad_input, None, None, None, None,)

class Group_normBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Group_normBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_input_idx = None
        self._saved_weight_idx = None
        self._num_groups = None
        self._eps = None

    def _save(self, *, input_=None, weight=None):
        tensors = []
        if input_ is not None:
            self._saved_input_idx = len(tensors)
            tensors.append(input_)
        if weight is not None:
            self._saved_weight_idx = len(tensors)
            tensors.append(weight)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        input_ = _saved[self._saved_input_idx]
        weight = _saved[self._saved_weight_idx] if self._saved_weight_idx is not None else None
        num_groups = self._num_groups
        eps = self._eps
        with _grad_context(keyset):
            grad_input = _group_norm_grad_input(grad, input_, num_groups, weight, eps, keyset)
        return (grad_input, None, None,)

class Rms_normBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Rms_normBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_input_idx = None
        self._saved_weight_idx = None
        self._normalized_shape = None
        self._eps = None

    def _save(self, *, input_=None, weight=None):
        tensors = []
        if input_ is not None:
            self._saved_input_idx = len(tensors)
            tensors.append(input_)
        if weight is not None:
            self._saved_weight_idx = len(tensors)
            tensors.append(weight)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        input_ = _saved[self._saved_input_idx]
        weight = _saved[self._saved_weight_idx] if self._saved_weight_idx is not None else None
        normalized_shape = self._normalized_shape
        eps = self._eps
        with _grad_context(keyset):
            grad_input = _rms_norm_grad_input(grad, input_, normalized_shape, weight, eps, keyset)
        return (grad_input, None,)

class Conv1dBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Conv1dBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_bias_idx = None
        self._saved_input_idx = None
        self._saved_weight_idx = None
        self._stride = None
        self._padding = None
        self._dilation = None
        self._groups = None

    def _save(self, *, bias=None, input_=None, weight=None):
        tensors = []
        if bias is not None:
            self._saved_bias_idx = len(tensors)
            tensors.append(bias)
        if input_ is not None:
            self._saved_input_idx = len(tensors)
            tensors.append(input_)
        if weight is not None:
            self._saved_weight_idx = len(tensors)
            tensors.append(weight)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        bias = _saved[self._saved_bias_idx] if self._saved_bias_idx is not None else None
        input_ = _saved[self._saved_input_idx]
        weight = _saved[self._saved_weight_idx]
        stride = self._stride
        padding = self._padding
        dilation = self._dilation
        groups = self._groups
        with _grad_context(keyset):
            grad_input, grad_weight, grad_bias = _conv_backward_all(grad, input_, weight, bias, stride, padding, dilation, groups, 'conv1d', keyset)
        return (grad_input, grad_weight, grad_bias,)

class Conv2dBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Conv2dBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_bias_idx = None
        self._saved_input_idx = None
        self._saved_weight_idx = None
        self._stride = None
        self._padding = None
        self._dilation = None
        self._groups = None

    def _save(self, *, bias=None, input_=None, weight=None):
        tensors = []
        if bias is not None:
            self._saved_bias_idx = len(tensors)
            tensors.append(bias)
        if input_ is not None:
            self._saved_input_idx = len(tensors)
            tensors.append(input_)
        if weight is not None:
            self._saved_weight_idx = len(tensors)
            tensors.append(weight)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        bias = _saved[self._saved_bias_idx] if self._saved_bias_idx is not None else None
        input_ = _saved[self._saved_input_idx]
        weight = _saved[self._saved_weight_idx]
        stride = self._stride
        padding = self._padding
        dilation = self._dilation
        groups = self._groups
        with _grad_context(keyset):
            grad_input, grad_weight, grad_bias = _conv_backward_all(grad, input_, weight, bias, stride, padding, dilation, groups, 'conv2d', keyset)
        return (grad_input, grad_weight, grad_bias,)

class Conv3dBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Conv3dBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_bias_idx = None
        self._saved_input_idx = None
        self._saved_weight_idx = None
        self._stride = None
        self._padding = None
        self._dilation = None
        self._groups = None

    def _save(self, *, bias=None, input_=None, weight=None):
        tensors = []
        if bias is not None:
            self._saved_bias_idx = len(tensors)
            tensors.append(bias)
        if input_ is not None:
            self._saved_input_idx = len(tensors)
            tensors.append(input_)
        if weight is not None:
            self._saved_weight_idx = len(tensors)
            tensors.append(weight)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        bias = _saved[self._saved_bias_idx] if self._saved_bias_idx is not None else None
        input_ = _saved[self._saved_input_idx]
        weight = _saved[self._saved_weight_idx]
        stride = self._stride
        padding = self._padding
        dilation = self._dilation
        groups = self._groups
        with _grad_context(keyset):
            grad_input, grad_weight, grad_bias = _conv_backward_all(grad, input_, weight, bias, stride, padding, dilation, groups, 'conv3d', keyset)
        return (grad_input, grad_weight, grad_bias,)

class Conv_transpose1dBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Conv_transpose1dBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_bias_idx = None
        self._saved_input_idx = None
        self._saved_weight_idx = None
        self._stride = None
        self._padding = None
        self._output_padding = None
        self._groups = None
        self._dilation = None

    def _save(self, *, bias=None, input_=None, weight=None):
        tensors = []
        if bias is not None:
            self._saved_bias_idx = len(tensors)
            tensors.append(bias)
        if input_ is not None:
            self._saved_input_idx = len(tensors)
            tensors.append(input_)
        if weight is not None:
            self._saved_weight_idx = len(tensors)
            tensors.append(weight)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        bias = _saved[self._saved_bias_idx] if self._saved_bias_idx is not None else None
        input_ = _saved[self._saved_input_idx]
        weight = _saved[self._saved_weight_idx]
        stride = self._stride
        padding = self._padding
        output_padding = self._output_padding
        groups = self._groups
        dilation = self._dilation
        with _grad_context(keyset):
            grad_input, grad_weight, grad_bias = _conv_backward_all(grad, input_, weight, bias, stride, padding, dilation, groups, 'conv_transpose1d', keyset)
        return (grad_input, grad_weight, grad_bias,)

class Conv_transpose2dBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Conv_transpose2dBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_bias_idx = None
        self._saved_input_idx = None
        self._saved_weight_idx = None
        self._stride = None
        self._padding = None
        self._output_padding = None
        self._groups = None
        self._dilation = None

    def _save(self, *, bias=None, input_=None, weight=None):
        tensors = []
        if bias is not None:
            self._saved_bias_idx = len(tensors)
            tensors.append(bias)
        if input_ is not None:
            self._saved_input_idx = len(tensors)
            tensors.append(input_)
        if weight is not None:
            self._saved_weight_idx = len(tensors)
            tensors.append(weight)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        bias = _saved[self._saved_bias_idx] if self._saved_bias_idx is not None else None
        input_ = _saved[self._saved_input_idx]
        weight = _saved[self._saved_weight_idx]
        stride = self._stride
        padding = self._padding
        output_padding = self._output_padding
        groups = self._groups
        dilation = self._dilation
        with _grad_context(keyset):
            grad_input, grad_weight, grad_bias = _conv_backward_all(grad, input_, weight, bias, stride, padding, dilation, groups, 'conv_transpose2d', keyset)
        return (grad_input, grad_weight, grad_bias,)

class Conv_transpose3dBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Conv_transpose3dBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_bias_idx = None
        self._saved_input_idx = None
        self._saved_weight_idx = None
        self._stride = None
        self._padding = None
        self._output_padding = None
        self._groups = None
        self._dilation = None

    def _save(self, *, bias=None, input_=None, weight=None):
        tensors = []
        if bias is not None:
            self._saved_bias_idx = len(tensors)
            tensors.append(bias)
        if input_ is not None:
            self._saved_input_idx = len(tensors)
            tensors.append(input_)
        if weight is not None:
            self._saved_weight_idx = len(tensors)
            tensors.append(weight)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        bias = _saved[self._saved_bias_idx] if self._saved_bias_idx is not None else None
        input_ = _saved[self._saved_input_idx]
        weight = _saved[self._saved_weight_idx]
        stride = self._stride
        padding = self._padding
        output_padding = self._output_padding
        groups = self._groups
        dilation = self._dilation
        with _grad_context(keyset):
            grad_input, grad_weight, grad_bias = _conv_backward_all(grad, input_, weight, bias, stride, padding, dilation, groups, 'conv_transpose3d', keyset)
        return (grad_input, grad_weight, grad_bias,)

class Max_pool1dBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Max_pool1dBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._saved_result_idx = None
        self._kernel_size = None
        self._stride = None
        self._padding = None
        self._dilation = None
        self._ceil_mode = None
        self._return_indices = None

    def _save(self, *, self_=None, result=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if result is not None:
            self._saved_result_idx = len(tensors)
            tensors.append(result)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        result = _saved[self._saved_result_idx]
        kernel_size = self._kernel_size
        stride = self._stride
        padding = self._padding
        dilation = self._dilation
        ceil_mode = self._ceil_mode
        return_indices = self._return_indices
        with _grad_context(keyset):
            grad_self = _max_pool1d_backward_helper(grad, self_, result, kernel_size, stride, padding, dilation, ceil_mode, keyset)
        return (grad_self,)

class Max_pool2dBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Max_pool2dBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._saved_result_idx = None
        self._kernel_size = None
        self._stride = None
        self._padding = None
        self._dilation = None
        self._ceil_mode = None
        self._return_indices = None

    def _save(self, *, self_=None, result=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if result is not None:
            self._saved_result_idx = len(tensors)
            tensors.append(result)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        result = _saved[self._saved_result_idx]
        kernel_size = self._kernel_size
        stride = self._stride
        padding = self._padding
        dilation = self._dilation
        ceil_mode = self._ceil_mode
        return_indices = self._return_indices
        with _grad_context(keyset):
            grad_self = _max_pool2d_backward_helper(grad, self_, result, kernel_size, stride, padding, dilation, ceil_mode, keyset)
        return (grad_self,)

class Max_pool3dBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Max_pool3dBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._saved_result_idx = None
        self._kernel_size = None
        self._stride = None
        self._padding = None
        self._dilation = None
        self._ceil_mode = None
        self._return_indices = None

    def _save(self, *, self_=None, result=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if result is not None:
            self._saved_result_idx = len(tensors)
            tensors.append(result)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        result = _saved[self._saved_result_idx]
        kernel_size = self._kernel_size
        stride = self._stride
        padding = self._padding
        dilation = self._dilation
        ceil_mode = self._ceil_mode
        return_indices = self._return_indices
        with _grad_context(keyset):
            grad_self = _max_pool3d_backward_helper(grad, self_, result, kernel_size, stride, padding, dilation, ceil_mode, keyset)
        return (grad_self,)

class Avg_pool1dBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Avg_pool1dBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._kernel_size = None
        self._stride = None
        self._padding = None
        self._ceil_mode = None
        self._count_include_pad = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        kernel_size = self._kernel_size
        stride = self._stride
        padding = self._padding
        ceil_mode = self._ceil_mode
        count_include_pad = self._count_include_pad
        with _grad_context(keyset):
            grad_self = _avg_pool1d_backward_helper(grad, self_, kernel_size, stride, padding, ceil_mode, count_include_pad, keyset)
        return (grad_self,)

class Avg_pool2dBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Avg_pool2dBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._kernel_size = None
        self._stride = None
        self._padding = None
        self._ceil_mode = None
        self._count_include_pad = None
        self._divisor_override = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        kernel_size = self._kernel_size
        stride = self._stride
        padding = self._padding
        ceil_mode = self._ceil_mode
        count_include_pad = self._count_include_pad
        divisor_override = self._divisor_override
        with _grad_context(keyset):
            grad_self = _avg_pool2d_backward_helper(grad, self_, kernel_size, stride, padding, ceil_mode, count_include_pad, keyset)
        return (grad_self,)

class Avg_pool3dBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Avg_pool3dBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._kernel_size = None
        self._stride = None
        self._padding = None
        self._ceil_mode = None
        self._count_include_pad = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        kernel_size = self._kernel_size
        stride = self._stride
        padding = self._padding
        ceil_mode = self._ceil_mode
        count_include_pad = self._count_include_pad
        with _grad_context(keyset):
            grad_self = _avg_pool3d_backward_helper(grad, self_, kernel_size, stride, padding, ceil_mode, count_include_pad, keyset)
        return (grad_self,)

class Adaptive_avg_pool1dBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Adaptive_avg_pool1dBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._output_size = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        output_size = self._output_size
        with _grad_context(keyset):
            grad_self = _adaptive_avg_pool1d_backward_helper(grad, self_, output_size, keyset)
        return (grad_self,)

class Adaptive_avg_pool2dBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Adaptive_avg_pool2dBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._output_size = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        output_size = self._output_size
        with _grad_context(keyset):
            grad_self = _adaptive_avg_pool2d_backward_helper(grad, self_, output_size, keyset)
        return (grad_self,)

class Adaptive_avg_pool3dBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Adaptive_avg_pool3dBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._output_size = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        output_size = self._output_size
        with _grad_context(keyset):
            grad_self = _adaptive_avg_pool3d_backward_helper(grad, self_, output_size, keyset)
        return (grad_self,)

class Adaptive_max_pool1dBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Adaptive_max_pool1dBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._saved_result_idx = None
        self._output_size = None
        self._return_indices = None

    def _save(self, *, self_=None, result=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if result is not None:
            self._saved_result_idx = len(tensors)
            tensors.append(result)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        result = _saved[self._saved_result_idx]
        output_size = self._output_size
        return_indices = self._return_indices
        with _grad_context(keyset):
            grad_self = _adaptive_max_pool1d_backward_helper(grad, self_, result, output_size, keyset)
        return (grad_self,)

class Adaptive_max_pool2dBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Adaptive_max_pool2dBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._saved_result_idx = None
        self._output_size = None
        self._return_indices = None

    def _save(self, *, self_=None, result=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if result is not None:
            self._saved_result_idx = len(tensors)
            tensors.append(result)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        result = _saved[self._saved_result_idx]
        output_size = self._output_size
        return_indices = self._return_indices
        with _grad_context(keyset):
            grad_self = _adaptive_max_pool2d_backward_helper(grad, self_, result, output_size, keyset)
        return (grad_self,)

class Upsample_nearest1dBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Upsample_nearest1dBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._output_size = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        output_size = self._output_size
        with _grad_context(keyset):
            grad_self = _upsample_nearest1d_backward_helper(grad, self_, output_size, keyset)
        return (grad_self,)

class Upsample_nearest2dBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Upsample_nearest2dBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._output_size = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        output_size = self._output_size
        with _grad_context(keyset):
            grad_self = _upsample_nearest2d_backward_helper(grad, self_, output_size, keyset)
        return (grad_self,)

class Upsample_bilinear2dBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Upsample_bilinear2dBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._output_size = None
        self._align_corners = None
        self._scales_h = None
        self._scales_w = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        output_size = self._output_size
        align_corners = self._align_corners
        scales_h = self._scales_h
        scales_w = self._scales_w
        with _grad_context(keyset):
            grad_self = _upsample_bilinear2d_backward_helper(grad, self_, output_size, align_corners, keyset)
        return (grad_self,)

class Upsample_linear1dBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Upsample_linear1dBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._output_size = None
        self._align_corners = None
        self._scales = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        output_size = self._output_size
        align_corners = self._align_corners
        scales = self._scales
        with _grad_context(keyset):
            grad_self = _upsample_linear1d_backward_helper(grad, self_, output_size, align_corners, keyset)
        return (grad_self,)

class Upsample_bicubic2dBackward0(Node):
    def __init__(self, inputs, *, raw_keyset=None, active_keyset=None):
        super().__init__(self.apply, inputs, name='Upsample_bicubic2dBackward0')
        self._raw_keyset = raw_keyset
        self._active_keyset = active_keyset
        self._saved_self_idx = None
        self._output_size = None
        self._align_corners = None
        self._scales_h = None
        self._scales_w = None

    def _save(self, *, self_=None):
        tensors = []
        if self_ is not None:
            self._saved_self_idx = len(tensors)
            tensors.append(self_)
        if tensors:
            super().save_for_backward(*tensors)

    def apply(self, grad):
        from .._dispatch.dispatcher import current_dispatch_keyset
        keyset = _backward_dispatch_keyset(self._raw_keyset, self._active_keyset)
        _saved = self.saved_tensors()
        self_ = _saved[self._saved_self_idx]
        output_size = self._output_size
        align_corners = self._align_corners
        scales_h = self._scales_h
        scales_w = self._scales_w
        with _grad_context(keyset):
            grad_self = _upsample_bicubic2d_backward_helper(grad, self_, output_size, align_corners, keyset)
        return (grad_self,)
