"""Auto-generated autograd kernel registration — DO NOT EDIT.

Generated by tools/autograd/gen_registration.py from derivatives.yaml.
"""



def register_generated_autograd_kernels():
    from .._dispatch.registration import register_autograd_kernels
    from . import variable_type as _VT

    register_autograd_kernels('exp', default=_VT.exp_autograd, cpu=_VT.exp_autograd, cuda=_VT.exp_autograd, meta=_VT.exp_autograd)
    register_autograd_kernels('log', default=_VT.log_autograd, cpu=_VT.log_autograd, cuda=_VT.log_autograd, meta=_VT.log_autograd)
    register_autograd_kernels('sqrt', default=_VT.sqrt_autograd, cpu=_VT.sqrt_autograd, cuda=_VT.sqrt_autograd, meta=_VT.sqrt_autograd)
    register_autograd_kernels('rsqrt', default=_VT.rsqrt_autograd, cpu=_VT.rsqrt_autograd, cuda=_VT.rsqrt_autograd, meta=_VT.rsqrt_autograd)
    register_autograd_kernels('neg', default=_VT.neg_autograd, cpu=_VT.neg_autograd, cuda=_VT.neg_autograd, meta=_VT.neg_autograd)
    register_autograd_kernels('abs', default=_VT.abs_autograd, cpu=_VT.abs_autograd, cuda=_VT.abs_autograd, meta=_VT.abs_autograd)
    register_autograd_kernels('sigmoid', default=_VT.sigmoid_autograd, cpu=_VT.sigmoid_autograd, cuda=_VT.sigmoid_autograd, meta=_VT.sigmoid_autograd)
    register_autograd_kernels('tanh', default=_VT.tanh_autograd, cpu=_VT.tanh_autograd, cuda=_VT.tanh_autograd, meta=_VT.tanh_autograd)
    register_autograd_kernels('sin', default=_VT.sin_autograd, cpu=_VT.sin_autograd, cuda=_VT.sin_autograd, meta=_VT.sin_autograd)
    register_autograd_kernels('cos', default=_VT.cos_autograd, cpu=_VT.cos_autograd, cuda=_VT.cos_autograd, meta=_VT.cos_autograd)
    register_autograd_kernels('relu', default=_VT.relu_autograd, cpu=_VT.relu_autograd, cuda=_VT.relu_autograd, meta=_VT.relu_autograd)
    register_autograd_kernels('add', default=_VT.add_autograd, cpu=_VT.add_autograd, cuda=_VT.add_autograd, meta=_VT.add_autograd)
    register_autograd_kernels('mul', default=_VT.mul_autograd, cpu=_VT.mul_autograd, cuda=_VT.mul_autograd, meta=_VT.mul_autograd)
    register_autograd_kernels('sub', default=_VT.sub_autograd, cpu=_VT.sub_autograd, cuda=_VT.sub_autograd, meta=_VT.sub_autograd)
    register_autograd_kernels('div', default=_VT.div_autograd, cpu=_VT.div_autograd, cuda=_VT.div_autograd, meta=_VT.div_autograd)
    register_autograd_kernels('matmul', default=_VT.matmul_autograd, cpu=_VT.matmul_autograd, cuda=_VT.matmul_autograd, meta=_VT.matmul_autograd)
    register_autograd_kernels('reshape', default=_VT.reshape_autograd, cpu=_VT.reshape_autograd, cuda=_VT.reshape_autograd, meta=_VT.reshape_autograd)
    register_autograd_kernels('transpose', default=_VT.transpose_autograd, cpu=_VT.transpose_autograd, cuda=_VT.transpose_autograd, meta=_VT.transpose_autograd)
    register_autograd_kernels('permute', default=_VT.permute_autograd, cpu=_VT.permute_autograd, cuda=_VT.permute_autograd, meta=_VT.permute_autograd)
    register_autograd_kernels('expand', default=_VT.expand_autograd, cpu=_VT.expand_autograd, cuda=_VT.expand_autograd, meta=_VT.expand_autograd)
    register_autograd_kernels('squeeze', default=_VT.squeeze_autograd, cpu=_VT.squeeze_autograd, cuda=_VT.squeeze_autograd, meta=_VT.squeeze_autograd)
    register_autograd_kernels('unsqueeze', default=_VT.unsqueeze_autograd, cpu=_VT.unsqueeze_autograd, cuda=_VT.unsqueeze_autograd, meta=_VT.unsqueeze_autograd)
    register_autograd_kernels('sum', default=_VT.sum_autograd, cpu=_VT.sum_autograd, cuda=_VT.sum_autograd, meta=_VT.sum_autograd)
    register_autograd_kernels('mean', default=_VT.mean_autograd, cpu=_VT.mean_autograd, cuda=_VT.mean_autograd, meta=_VT.mean_autograd)
    register_autograd_kernels('contiguous', default=_VT.contiguous_autograd, cpu=_VT.contiguous_autograd, cuda=_VT.contiguous_autograd, meta=_VT.contiguous_autograd)
    register_autograd_kernels('erf', default=_VT.erf_autograd, cpu=_VT.erf_autograd, cuda=_VT.erf_autograd, meta=_VT.erf_autograd)
    register_autograd_kernels('softplus', default=_VT.softplus_autograd, cpu=_VT.softplus_autograd, cuda=_VT.softplus_autograd, meta=_VT.softplus_autograd)
    register_autograd_kernels('silu', default=_VT.silu_autograd, cpu=_VT.silu_autograd, cuda=_VT.silu_autograd, meta=_VT.silu_autograd)
    register_autograd_kernels('gelu', default=_VT.gelu_autograd, cpu=_VT.gelu_autograd, cuda=_VT.gelu_autograd, meta=_VT.gelu_autograd)
    register_autograd_kernels('mish', default=_VT.mish_autograd, cpu=_VT.mish_autograd, cuda=_VT.mish_autograd, meta=_VT.mish_autograd)
    register_autograd_kernels('leaky_relu', default=_VT.leaky_relu_autograd, cpu=_VT.leaky_relu_autograd, cuda=_VT.leaky_relu_autograd, meta=_VT.leaky_relu_autograd)
    register_autograd_kernels('elu', default=_VT.elu_autograd, cpu=_VT.elu_autograd, cuda=_VT.elu_autograd, meta=_VT.elu_autograd)
    register_autograd_kernels('celu', default=_VT.celu_autograd, cpu=_VT.celu_autograd, cuda=_VT.celu_autograd, meta=_VT.celu_autograd)
    register_autograd_kernels('hardtanh', default=_VT.hardtanh_autograd, cpu=_VT.hardtanh_autograd, cuda=_VT.hardtanh_autograd, meta=_VT.hardtanh_autograd)
    register_autograd_kernels('relu6', default=_VT.relu6_autograd, cpu=_VT.relu6_autograd, cuda=_VT.relu6_autograd, meta=_VT.relu6_autograd)
    register_autograd_kernels('hardswish', default=_VT.hardswish_autograd, cpu=_VT.hardswish_autograd, cuda=_VT.hardswish_autograd, meta=_VT.hardswish_autograd)
    register_autograd_kernels('hardsigmoid', default=_VT.hardsigmoid_autograd, cpu=_VT.hardsigmoid_autograd, cuda=_VT.hardsigmoid_autograd, meta=_VT.hardsigmoid_autograd)
    register_autograd_kernels('selu', default=_VT.selu_autograd, cpu=_VT.selu_autograd, cuda=_VT.selu_autograd, meta=_VT.selu_autograd)
    register_autograd_kernels('softmax', default=_VT.softmax_autograd, cpu=_VT.softmax_autograd, cuda=_VT.softmax_autograd, meta=_VT.softmax_autograd)
    register_autograd_kernels('log_softmax', default=_VT.log_softmax_autograd, cpu=_VT.log_softmax_autograd, cuda=_VT.log_softmax_autograd, meta=_VT.log_softmax_autograd)
    register_autograd_kernels('prelu', default=_VT.prelu_autograd, cpu=_VT.prelu_autograd, cuda=_VT.prelu_autograd, meta=_VT.prelu_autograd)
    register_autograd_kernels('layer_norm', default=_VT.layer_norm_autograd, cpu=_VT.layer_norm_autograd, cuda=_VT.layer_norm_autograd, meta=_VT.layer_norm_autograd)
    register_autograd_kernels('batch_norm', default=_VT.batch_norm_autograd, cpu=_VT.batch_norm_autograd, cuda=_VT.batch_norm_autograd, meta=_VT.batch_norm_autograd)
    register_autograd_kernels('group_norm', default=_VT.group_norm_autograd, cpu=_VT.group_norm_autograd, cuda=_VT.group_norm_autograd, meta=_VT.group_norm_autograd)
    register_autograd_kernels('rms_norm', default=_VT.rms_norm_autograd, cpu=_VT.rms_norm_autograd, cuda=_VT.rms_norm_autograd, meta=_VT.rms_norm_autograd)
