"""Auto-generated autograd kernel registration — DO NOT EDIT.

Generated by tools/autograd/gen_registration.py from derivatives.yaml.
"""



def register_generated_autograd_kernels(only_ops=None):
    from .._dispatch.registration import register_autograd_kernels
    from . import variable_type as _VT

    if only_ops is None or 'exp' in only_ops:
        register_autograd_kernels('exp', default=_VT.exp_autograd, cpu=_VT.exp_autograd, cuda=_VT.exp_autograd, meta=_VT.exp_autograd)
    if only_ops is None or 'log' in only_ops:
        register_autograd_kernels('log', default=_VT.log_autograd, cpu=_VT.log_autograd, cuda=_VT.log_autograd, meta=_VT.log_autograd)
    if only_ops is None or 'sqrt' in only_ops:
        register_autograd_kernels('sqrt', default=_VT.sqrt_autograd, cpu=_VT.sqrt_autograd, cuda=_VT.sqrt_autograd, meta=_VT.sqrt_autograd)
    if only_ops is None or 'rsqrt' in only_ops:
        register_autograd_kernels('rsqrt', default=_VT.rsqrt_autograd, cpu=_VT.rsqrt_autograd, cuda=_VT.rsqrt_autograd, meta=_VT.rsqrt_autograd)
    if only_ops is None or 'neg' in only_ops:
        register_autograd_kernels('neg', default=_VT.neg_autograd, cpu=_VT.neg_autograd, cuda=_VT.neg_autograd, meta=_VT.neg_autograd)
    if only_ops is None or 'abs' in only_ops:
        register_autograd_kernels('abs', default=_VT.abs_autograd, cpu=_VT.abs_autograd, cuda=_VT.abs_autograd, meta=_VT.abs_autograd)
    if only_ops is None or 'sigmoid' in only_ops:
        register_autograd_kernels('sigmoid', default=_VT.sigmoid_autograd, cpu=_VT.sigmoid_autograd, cuda=_VT.sigmoid_autograd, meta=_VT.sigmoid_autograd)
    if only_ops is None or 'tanh' in only_ops:
        register_autograd_kernels('tanh', default=_VT.tanh_autograd, cpu=_VT.tanh_autograd, cuda=_VT.tanh_autograd, meta=_VT.tanh_autograd)
    if only_ops is None or 'sin' in only_ops:
        register_autograd_kernels('sin', default=_VT.sin_autograd, cpu=_VT.sin_autograd, cuda=_VT.sin_autograd, meta=_VT.sin_autograd)
    if only_ops is None or 'cos' in only_ops:
        register_autograd_kernels('cos', default=_VT.cos_autograd, cpu=_VT.cos_autograd, cuda=_VT.cos_autograd, meta=_VT.cos_autograd)
    if only_ops is None or 'relu' in only_ops:
        register_autograd_kernels('relu', default=_VT.relu_autograd, cpu=_VT.relu_autograd, cuda=_VT.relu_autograd, meta=_VT.relu_autograd)
    if only_ops is None or 'add' in only_ops:
        register_autograd_kernels('add', default=_VT.add_autograd, cpu=_VT.add_autograd, cuda=_VT.add_autograd, meta=_VT.add_autograd)
    if only_ops is None or 'mul' in only_ops:
        register_autograd_kernels('mul', default=_VT.mul_autograd, cpu=_VT.mul_autograd, cuda=_VT.mul_autograd, meta=_VT.mul_autograd)
    if only_ops is None or 'sub' in only_ops:
        register_autograd_kernels('sub', default=_VT.sub_autograd, cpu=_VT.sub_autograd, cuda=_VT.sub_autograd, meta=_VT.sub_autograd)
    if only_ops is None or 'div' in only_ops:
        register_autograd_kernels('div', default=_VT.div_autograd, cpu=_VT.div_autograd, cuda=_VT.div_autograd, meta=_VT.div_autograd)
    if only_ops is None or 'matmul' in only_ops:
        register_autograd_kernels('matmul', default=_VT.matmul_autograd, cpu=_VT.matmul_autograd, cuda=_VT.matmul_autograd, meta=_VT.matmul_autograd)
    if only_ops is None or 'reshape' in only_ops:
        register_autograd_kernels('reshape', default=_VT.reshape_autograd, cpu=_VT.reshape_autograd, cuda=_VT.reshape_autograd, meta=_VT.reshape_autograd)
    if only_ops is None or 'transpose' in only_ops:
        register_autograd_kernels('transpose', default=_VT.transpose_autograd, cpu=_VT.transpose_autograd, cuda=_VT.transpose_autograd, meta=_VT.transpose_autograd)
    if only_ops is None or 'permute' in only_ops:
        register_autograd_kernels('permute', default=_VT.permute_autograd, cpu=_VT.permute_autograd, cuda=_VT.permute_autograd, meta=_VT.permute_autograd)
    if only_ops is None or 'expand' in only_ops:
        register_autograd_kernels('expand', default=_VT.expand_autograd, cpu=_VT.expand_autograd, cuda=_VT.expand_autograd, meta=_VT.expand_autograd)
    if only_ops is None or 'squeeze' in only_ops:
        register_autograd_kernels('squeeze', default=_VT.squeeze_autograd, cpu=_VT.squeeze_autograd, cuda=_VT.squeeze_autograd, meta=_VT.squeeze_autograd)
    if only_ops is None or 'unsqueeze' in only_ops:
        register_autograd_kernels('unsqueeze', default=_VT.unsqueeze_autograd, cpu=_VT.unsqueeze_autograd, cuda=_VT.unsqueeze_autograd, meta=_VT.unsqueeze_autograd)
    if only_ops is None or 'sum' in only_ops:
        register_autograd_kernels('sum', default=_VT.sum_autograd, cpu=_VT.sum_autograd, cuda=_VT.sum_autograd, meta=_VT.sum_autograd)
    if only_ops is None or 'mean' in only_ops:
        register_autograd_kernels('mean', default=_VT.mean_autograd, cpu=_VT.mean_autograd, cuda=_VT.mean_autograd, meta=_VT.mean_autograd)
    if only_ops is None or 'contiguous' in only_ops:
        register_autograd_kernels('contiguous', default=_VT.contiguous_autograd, cpu=_VT.contiguous_autograd, cuda=_VT.contiguous_autograd, meta=_VT.contiguous_autograd)
    if only_ops is None or 'erf' in only_ops:
        register_autograd_kernels('erf', default=_VT.erf_autograd, cpu=_VT.erf_autograd, cuda=_VT.erf_autograd, meta=_VT.erf_autograd)
    if only_ops is None or 'softplus' in only_ops:
        register_autograd_kernels('softplus', default=_VT.softplus_autograd, cpu=_VT.softplus_autograd, cuda=_VT.softplus_autograd, meta=_VT.softplus_autograd)
    if only_ops is None or 'silu' in only_ops:
        register_autograd_kernels('silu', default=_VT.silu_autograd, cpu=_VT.silu_autograd, cuda=_VT.silu_autograd, meta=_VT.silu_autograd)
    if only_ops is None or 'gelu' in only_ops:
        register_autograd_kernels('gelu', default=_VT.gelu_autograd, cpu=_VT.gelu_autograd, cuda=_VT.gelu_autograd, meta=_VT.gelu_autograd)
    if only_ops is None or 'mish' in only_ops:
        register_autograd_kernels('mish', default=_VT.mish_autograd, cpu=_VT.mish_autograd, cuda=_VT.mish_autograd, meta=_VT.mish_autograd)
    if only_ops is None or 'leaky_relu' in only_ops:
        register_autograd_kernels('leaky_relu', default=_VT.leaky_relu_autograd, cpu=_VT.leaky_relu_autograd, cuda=_VT.leaky_relu_autograd, meta=_VT.leaky_relu_autograd)
    if only_ops is None or 'elu' in only_ops:
        register_autograd_kernels('elu', default=_VT.elu_autograd, cpu=_VT.elu_autograd, cuda=_VT.elu_autograd, meta=_VT.elu_autograd)
    if only_ops is None or 'celu' in only_ops:
        register_autograd_kernels('celu', default=_VT.celu_autograd, cpu=_VT.celu_autograd, cuda=_VT.celu_autograd, meta=_VT.celu_autograd)
    if only_ops is None or 'hardtanh' in only_ops:
        register_autograd_kernels('hardtanh', default=_VT.hardtanh_autograd, cpu=_VT.hardtanh_autograd, cuda=_VT.hardtanh_autograd, meta=_VT.hardtanh_autograd)
    if only_ops is None or 'relu6' in only_ops:
        register_autograd_kernels('relu6', default=_VT.relu6_autograd, cpu=_VT.relu6_autograd, cuda=_VT.relu6_autograd, meta=_VT.relu6_autograd)
    if only_ops is None or 'hardswish' in only_ops:
        register_autograd_kernels('hardswish', default=_VT.hardswish_autograd, cpu=_VT.hardswish_autograd, cuda=_VT.hardswish_autograd, meta=_VT.hardswish_autograd)
    if only_ops is None or 'hardsigmoid' in only_ops:
        register_autograd_kernels('hardsigmoid', default=_VT.hardsigmoid_autograd, cpu=_VT.hardsigmoid_autograd, cuda=_VT.hardsigmoid_autograd, meta=_VT.hardsigmoid_autograd)
    if only_ops is None or 'selu' in only_ops:
        register_autograd_kernels('selu', default=_VT.selu_autograd, cpu=_VT.selu_autograd, cuda=_VT.selu_autograd, meta=_VT.selu_autograd)
    if only_ops is None or 'softmax' in only_ops:
        register_autograd_kernels('softmax', default=_VT.softmax_autograd, cpu=_VT.softmax_autograd, cuda=_VT.softmax_autograd, meta=_VT.softmax_autograd)
    if only_ops is None or 'log_softmax' in only_ops:
        register_autograd_kernels('log_softmax', default=_VT.log_softmax_autograd, cpu=_VT.log_softmax_autograd, cuda=_VT.log_softmax_autograd, meta=_VT.log_softmax_autograd)
    if only_ops is None or 'prelu' in only_ops:
        register_autograd_kernels('prelu', default=_VT.prelu_autograd, cpu=_VT.prelu_autograd, cuda=_VT.prelu_autograd, meta=_VT.prelu_autograd)
    if only_ops is None or 'layer_norm' in only_ops:
        register_autograd_kernels('layer_norm', default=_VT.layer_norm_autograd, cpu=_VT.layer_norm_autograd, cuda=_VT.layer_norm_autograd, meta=_VT.layer_norm_autograd)
    if only_ops is None or 'batch_norm' in only_ops:
        register_autograd_kernels('batch_norm', default=_VT.batch_norm_autograd, cpu=_VT.batch_norm_autograd, cuda=_VT.batch_norm_autograd, meta=_VT.batch_norm_autograd)
    if only_ops is None or 'group_norm' in only_ops:
        register_autograd_kernels('group_norm', default=_VT.group_norm_autograd, cpu=_VT.group_norm_autograd, cuda=_VT.group_norm_autograd, meta=_VT.group_norm_autograd)
    if only_ops is None or 'rms_norm' in only_ops:
        register_autograd_kernels('rms_norm', default=_VT.rms_norm_autograd, cpu=_VT.rms_norm_autograd, cuda=_VT.rms_norm_autograd, meta=_VT.rms_norm_autograd)
    if only_ops is None or 'conv1d' in only_ops:
        register_autograd_kernels('conv1d', default=_VT.conv1d_autograd, cpu=_VT.conv1d_autograd, cuda=_VT.conv1d_autograd, meta=_VT.conv1d_autograd)
    if only_ops is None or 'conv2d' in only_ops:
        register_autograd_kernels('conv2d', default=_VT.conv2d_autograd, cpu=_VT.conv2d_autograd, cuda=_VT.conv2d_autograd, meta=_VT.conv2d_autograd)
    if only_ops is None or 'conv3d' in only_ops:
        register_autograd_kernels('conv3d', default=_VT.conv3d_autograd, cpu=_VT.conv3d_autograd, cuda=_VT.conv3d_autograd, meta=_VT.conv3d_autograd)
    if only_ops is None or 'conv_transpose1d' in only_ops:
        register_autograd_kernels('conv_transpose1d', default=_VT.conv_transpose1d_autograd, cpu=_VT.conv_transpose1d_autograd, cuda=_VT.conv_transpose1d_autograd, meta=_VT.conv_transpose1d_autograd)
    if only_ops is None or 'conv_transpose2d' in only_ops:
        register_autograd_kernels('conv_transpose2d', default=_VT.conv_transpose2d_autograd, cpu=_VT.conv_transpose2d_autograd, cuda=_VT.conv_transpose2d_autograd, meta=_VT.conv_transpose2d_autograd)
    if only_ops is None or 'conv_transpose3d' in only_ops:
        register_autograd_kernels('conv_transpose3d', default=_VT.conv_transpose3d_autograd, cpu=_VT.conv_transpose3d_autograd, cuda=_VT.conv_transpose3d_autograd, meta=_VT.conv_transpose3d_autograd)
    if only_ops is None or 'max_pool1d' in only_ops:
        register_autograd_kernels('max_pool1d', default=_VT.max_pool1d_autograd, cpu=_VT.max_pool1d_autograd, cuda=_VT.max_pool1d_autograd, meta=_VT.max_pool1d_autograd)
    if only_ops is None or 'max_pool2d' in only_ops:
        register_autograd_kernels('max_pool2d', default=_VT.max_pool2d_autograd, cpu=_VT.max_pool2d_autograd, cuda=_VT.max_pool2d_autograd, meta=_VT.max_pool2d_autograd)
    if only_ops is None or 'max_pool3d' in only_ops:
        register_autograd_kernels('max_pool3d', default=_VT.max_pool3d_autograd, cpu=_VT.max_pool3d_autograd, cuda=_VT.max_pool3d_autograd, meta=_VT.max_pool3d_autograd)
    if only_ops is None or 'avg_pool1d' in only_ops:
        register_autograd_kernels('avg_pool1d', default=_VT.avg_pool1d_autograd, cpu=_VT.avg_pool1d_autograd, cuda=_VT.avg_pool1d_autograd, meta=_VT.avg_pool1d_autograd)
    if only_ops is None or 'avg_pool2d' in only_ops:
        register_autograd_kernels('avg_pool2d', default=_VT.avg_pool2d_autograd, cpu=_VT.avg_pool2d_autograd, cuda=_VT.avg_pool2d_autograd, meta=_VT.avg_pool2d_autograd)
    if only_ops is None or 'avg_pool3d' in only_ops:
        register_autograd_kernels('avg_pool3d', default=_VT.avg_pool3d_autograd, cpu=_VT.avg_pool3d_autograd, cuda=_VT.avg_pool3d_autograd, meta=_VT.avg_pool3d_autograd)
    if only_ops is None or 'adaptive_avg_pool1d' in only_ops:
        register_autograd_kernels('adaptive_avg_pool1d', default=_VT.adaptive_avg_pool1d_autograd, cpu=_VT.adaptive_avg_pool1d_autograd, cuda=_VT.adaptive_avg_pool1d_autograd, meta=_VT.adaptive_avg_pool1d_autograd)
    if only_ops is None or 'adaptive_avg_pool2d' in only_ops:
        register_autograd_kernels('adaptive_avg_pool2d', default=_VT.adaptive_avg_pool2d_autograd, cpu=_VT.adaptive_avg_pool2d_autograd, cuda=_VT.adaptive_avg_pool2d_autograd, meta=_VT.adaptive_avg_pool2d_autograd)
    if only_ops is None or 'adaptive_avg_pool3d' in only_ops:
        register_autograd_kernels('adaptive_avg_pool3d', default=_VT.adaptive_avg_pool3d_autograd, cpu=_VT.adaptive_avg_pool3d_autograd, cuda=_VT.adaptive_avg_pool3d_autograd, meta=_VT.adaptive_avg_pool3d_autograd)
    if only_ops is None or 'adaptive_max_pool1d' in only_ops:
        register_autograd_kernels('adaptive_max_pool1d', default=_VT.adaptive_max_pool1d_autograd, cpu=_VT.adaptive_max_pool1d_autograd, cuda=_VT.adaptive_max_pool1d_autograd, meta=_VT.adaptive_max_pool1d_autograd)
    if only_ops is None or 'adaptive_max_pool2d' in only_ops:
        register_autograd_kernels('adaptive_max_pool2d', default=_VT.adaptive_max_pool2d_autograd, cpu=_VT.adaptive_max_pool2d_autograd, cuda=_VT.adaptive_max_pool2d_autograd, meta=_VT.adaptive_max_pool2d_autograd)
    if only_ops is None or 'upsample_nearest1d' in only_ops:
        register_autograd_kernels('upsample_nearest1d', default=_VT.upsample_nearest1d_autograd, cpu=_VT.upsample_nearest1d_autograd, cuda=_VT.upsample_nearest1d_autograd, meta=_VT.upsample_nearest1d_autograd)
    if only_ops is None or 'upsample_nearest2d' in only_ops:
        register_autograd_kernels('upsample_nearest2d', default=_VT.upsample_nearest2d_autograd, cpu=_VT.upsample_nearest2d_autograd, cuda=_VT.upsample_nearest2d_autograd, meta=_VT.upsample_nearest2d_autograd)
    if only_ops is None or 'upsample_bilinear2d' in only_ops:
        register_autograd_kernels('upsample_bilinear2d', default=_VT.upsample_bilinear2d_autograd, cpu=_VT.upsample_bilinear2d_autograd, cuda=_VT.upsample_bilinear2d_autograd, meta=_VT.upsample_bilinear2d_autograd)
    if only_ops is None or 'upsample_linear1d' in only_ops:
        register_autograd_kernels('upsample_linear1d', default=_VT.upsample_linear1d_autograd, cpu=_VT.upsample_linear1d_autograd, cuda=_VT.upsample_linear1d_autograd, meta=_VT.upsample_linear1d_autograd)
    if only_ops is None or 'upsample_bicubic2d' in only_ops:
        register_autograd_kernels('upsample_bicubic2d', default=_VT.upsample_bicubic2d_autograd, cpu=_VT.upsample_bicubic2d_autograd, cuda=_VT.upsample_bicubic2d_autograd, meta=_VT.upsample_bicubic2d_autograd)
