"""Auto-generated forward autograd wrappers — DO NOT EDIT.

Generated by tools/autograd/gen_variable_type.py from derivatives.yaml.
"""
from __future__ import annotations

from ..autograd.grad_mode import GradMode
from ..autograd.anomaly_mode import annotate_node_creation
from .._backends.autograd import _strip_autograd_keys
from .._dispatch.dispatcher import current_dispatch_keyset, redispatch
from . import functions as _F



def exp_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("exp", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.ExpBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(result=result)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def log_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("log", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.LogBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def sqrt_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("sqrt", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.SqrtBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def rsqrt_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("rsqrt", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.RsqrtBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def neg_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("neg", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.NegBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def abs_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("abs", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.AbsBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def sigmoid_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("sigmoid", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.SigmoidBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def tanh_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("tanh", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.TanhBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def sin_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("sin", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.SinBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def cos_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("cos", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.CosBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def relu_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("relu", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.ReluBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def add_autograd(self, other):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("add", raw_keyset, self, other)
    if GradMode.enabled and (getattr(self, 'requires_grad', False) or getattr(other, 'requires_grad', False)):
        grad_fn = _F.AddBackward0((self, other,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self, other=other)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def mul_autograd(self, other):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("mul", raw_keyset, self, other)
    if GradMode.enabled and (getattr(self, 'requires_grad', False) or getattr(other, 'requires_grad', False)):
        grad_fn = _F.MulBackward0((self, other,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(other=other, self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def sub_autograd(self, other):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("sub", raw_keyset, self, other)
    if GradMode.enabled and (getattr(self, 'requires_grad', False) or getattr(other, 'requires_grad', False)):
        grad_fn = _F.SubBackward0((self, other,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self, other=other)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def div_autograd(self, other):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("div", raw_keyset, self, other)
    if GradMode.enabled and (getattr(self, 'requires_grad', False) or getattr(other, 'requires_grad', False)):
        grad_fn = _F.DivBackward0((self, other,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(other=other, self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def matmul_autograd(self, other):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("matmul", raw_keyset, self, other)
    if GradMode.enabled and (getattr(self, 'requires_grad', False) or getattr(other, 'requires_grad', False)):
        grad_fn = _F.MatmulBackward0((self, other,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(other=other, self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def reshape_autograd(self, shape):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("reshape", raw_keyset, self, shape)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.ReshapeBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._shape = shape
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def transpose_autograd(self, dim0, dim1):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("transpose", raw_keyset, self, dim0, dim1)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.TransposeBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._dim0 = dim0
        grad_fn._dim1 = dim1
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def permute_autograd(self, dims):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("permute", raw_keyset, self, dims)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.PermuteBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._dims = dims
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def expand_autograd(self, size):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("expand", raw_keyset, self, size)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.ExpandBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._size = size
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def squeeze_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("squeeze", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.SqueezeBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def unsqueeze_autograd(self, dim):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("unsqueeze", raw_keyset, self, dim)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.UnsqueezeBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._dim = dim
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def sum_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("sum", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.SumBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def mean_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("mean", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.MeanBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def contiguous_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("contiguous", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.ContiguousBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def erf_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("erf", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.ErfBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def softplus_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("softplus", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.SoftplusBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def silu_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("silu", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.SiluBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def gelu_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("gelu", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.GeluBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def mish_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("mish", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.MishBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def leaky_relu_autograd(self, negative_slope=0.01):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("leaky_relu", raw_keyset, self, negative_slope)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.Leaky_reluBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._negative_slope = negative_slope
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def elu_autograd(self, alpha=1.0):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("elu", raw_keyset, self, alpha)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.EluBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._alpha = alpha
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def celu_autograd(self, alpha=1.0):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("celu", raw_keyset, self, alpha)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.CeluBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._alpha = alpha
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def hardtanh_autograd(self, min_val=-1.0, max_val=1.0):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("hardtanh", raw_keyset, self, min_val, max_val)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.HardtanhBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._min_val = min_val
        grad_fn._max_val = max_val
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def relu6_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("relu6", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.Relu6Backward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def hardswish_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("hardswish", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.HardswishBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def hardsigmoid_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("hardsigmoid", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.HardsigmoidBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def selu_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("selu", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.SeluBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def softmax_autograd(self, dim):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("softmax", raw_keyset, self, dim)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.SoftmaxBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._dim = dim
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def log_softmax_autograd(self, dim):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("log_softmax", raw_keyset, self, dim)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.Log_softmaxBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._dim = dim
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def prelu_autograd(self, weight):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("prelu", raw_keyset, self, weight)
    if GradMode.enabled and (getattr(self, 'requires_grad', False) or getattr(weight, 'requires_grad', False)):
        grad_fn = _F.PreluBackward0((self, weight,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self, weight=weight)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def layer_norm_autograd(input, normalized_shape, weight, bias, eps=1e-5):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("layer_norm", raw_keyset, input, normalized_shape, weight, bias, eps)
    if GradMode.enabled and (input.requires_grad):
        grad_fn = _F.Layer_normBackward0((input,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(input_=input, weight=weight)
        grad_fn._normalized_shape = normalized_shape
        grad_fn._eps = eps
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def batch_norm_autograd(input, running_mean, running_var, weight, bias, training=False, momentum=0.1, eps=1e-5):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("batch_norm", raw_keyset, input, running_mean, running_var, weight, bias, training, momentum, eps)
    if GradMode.enabled and (input.requires_grad):
        grad_fn = _F.Batch_normBackward0((input,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(input_=input, weight=weight)
        grad_fn._training = training
        grad_fn._momentum = momentum
        grad_fn._eps = eps
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def group_norm_autograd(input, num_groups, weight, bias, eps=1e-5):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("group_norm", raw_keyset, input, num_groups, weight, bias, eps)
    if GradMode.enabled and (input.requires_grad):
        grad_fn = _F.Group_normBackward0((input,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(input_=input, weight=weight)
        grad_fn._num_groups = num_groups
        grad_fn._eps = eps
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def rms_norm_autograd(input, normalized_shape, weight, eps=1e-6):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("rms_norm", raw_keyset, input, normalized_shape, weight, eps)
    if GradMode.enabled and (input.requires_grad):
        grad_fn = _F.Rms_normBackward0((input,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(input_=input, weight=weight)
        grad_fn._normalized_shape = normalized_shape
        grad_fn._eps = eps
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def conv1d_autograd(input, weight, bias=None, stride=None, padding=None, dilation=None, groups=1):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("conv1d", raw_keyset, input, weight, bias, stride, padding, dilation, groups)
    if GradMode.enabled and (getattr(input, 'requires_grad', False) or getattr(weight, 'requires_grad', False) or (bias is not None and getattr(bias, 'requires_grad', False))):
        _inputs = [x for x in (input, weight, bias,) if x is not None]
        grad_fn = _F.Conv1dBackward0(_inputs, raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(bias=bias, input_=input, weight=weight)
        grad_fn._stride = stride
        grad_fn._padding = padding
        grad_fn._dilation = dilation
        grad_fn._groups = groups
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def conv2d_autograd(input, weight, bias=None, stride=None, padding=None, dilation=None, groups=1):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("conv2d", raw_keyset, input, weight, bias, stride, padding, dilation, groups)
    if GradMode.enabled and (getattr(input, 'requires_grad', False) or getattr(weight, 'requires_grad', False) or (bias is not None and getattr(bias, 'requires_grad', False))):
        _inputs = [x for x in (input, weight, bias,) if x is not None]
        grad_fn = _F.Conv2dBackward0(_inputs, raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(bias=bias, input_=input, weight=weight)
        grad_fn._stride = stride
        grad_fn._padding = padding
        grad_fn._dilation = dilation
        grad_fn._groups = groups
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def conv3d_autograd(input, weight, bias, stride, padding, dilation, groups=1):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("conv3d", raw_keyset, input, weight, bias, stride, padding, dilation, groups)
    if GradMode.enabled and (getattr(input, 'requires_grad', False) or getattr(weight, 'requires_grad', False) or (bias is not None and getattr(bias, 'requires_grad', False))):
        _inputs = [x for x in (input, weight, bias,) if x is not None]
        grad_fn = _F.Conv3dBackward0(_inputs, raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(bias=bias, input_=input, weight=weight)
        grad_fn._stride = stride
        grad_fn._padding = padding
        grad_fn._dilation = dilation
        grad_fn._groups = groups
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def conv_transpose1d_autograd(input, weight, bias=None, stride=None, padding=None, output_padding=None, groups=1, dilation=None):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("conv_transpose1d", raw_keyset, input, weight, bias, stride, padding, output_padding, groups, dilation)
    if GradMode.enabled and (getattr(input, 'requires_grad', False) or getattr(weight, 'requires_grad', False) or (bias is not None and getattr(bias, 'requires_grad', False))):
        _inputs = [x for x in (input, weight, bias,) if x is not None]
        grad_fn = _F.Conv_transpose1dBackward0(_inputs, raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(bias=bias, input_=input, weight=weight)
        grad_fn._stride = stride
        grad_fn._padding = padding
        grad_fn._output_padding = output_padding
        grad_fn._groups = groups
        grad_fn._dilation = dilation
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def conv_transpose2d_autograd(input, weight, bias=None, stride=None, padding=None, output_padding=None, groups=1, dilation=None):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("conv_transpose2d", raw_keyset, input, weight, bias, stride, padding, output_padding, groups, dilation)
    if GradMode.enabled and (getattr(input, 'requires_grad', False) or getattr(weight, 'requires_grad', False) or (bias is not None and getattr(bias, 'requires_grad', False))):
        _inputs = [x for x in (input, weight, bias,) if x is not None]
        grad_fn = _F.Conv_transpose2dBackward0(_inputs, raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(bias=bias, input_=input, weight=weight)
        grad_fn._stride = stride
        grad_fn._padding = padding
        grad_fn._output_padding = output_padding
        grad_fn._groups = groups
        grad_fn._dilation = dilation
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def conv_transpose3d_autograd(input, weight, bias=None, stride=None, padding=None, output_padding=None, groups=1, dilation=None):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("conv_transpose3d", raw_keyset, input, weight, bias, stride, padding, output_padding, groups, dilation)
    if GradMode.enabled and (getattr(input, 'requires_grad', False) or getattr(weight, 'requires_grad', False) or (bias is not None and getattr(bias, 'requires_grad', False))):
        _inputs = [x for x in (input, weight, bias,) if x is not None]
        grad_fn = _F.Conv_transpose3dBackward0(_inputs, raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(bias=bias, input_=input, weight=weight)
        grad_fn._stride = stride
        grad_fn._padding = padding
        grad_fn._output_padding = output_padding
        grad_fn._groups = groups
        grad_fn._dilation = dilation
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def max_pool1d_autograd(self, kernel_size, stride, padding, dilation, ceil_mode=False, return_indices=False):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("max_pool1d", raw_keyset, self, kernel_size, stride, padding, dilation, ceil_mode, return_indices)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.Max_pool1dBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self, result=result)
        grad_fn._kernel_size = kernel_size
        grad_fn._stride = stride
        grad_fn._padding = padding
        grad_fn._dilation = dilation
        grad_fn._ceil_mode = ceil_mode
        grad_fn._return_indices = return_indices
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def max_pool2d_autograd(self, kernel_size, stride, padding=None, dilation=None, ceil_mode=False, return_indices=False):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("max_pool2d", raw_keyset, self, kernel_size, stride, padding, dilation, ceil_mode, return_indices)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.Max_pool2dBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self, result=result)
        grad_fn._kernel_size = kernel_size
        grad_fn._stride = stride
        grad_fn._padding = padding
        grad_fn._dilation = dilation
        grad_fn._ceil_mode = ceil_mode
        grad_fn._return_indices = return_indices
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def max_pool3d_autograd(self, kernel_size, stride, padding=None, dilation=None, ceil_mode=False, return_indices=False):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("max_pool3d", raw_keyset, self, kernel_size, stride, padding, dilation, ceil_mode, return_indices)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.Max_pool3dBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self, result=result)
        grad_fn._kernel_size = kernel_size
        grad_fn._stride = stride
        grad_fn._padding = padding
        grad_fn._dilation = dilation
        grad_fn._ceil_mode = ceil_mode
        grad_fn._return_indices = return_indices
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def avg_pool1d_autograd(self, kernel_size, stride, padding, ceil_mode=False, count_include_pad=True):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("avg_pool1d", raw_keyset, self, kernel_size, stride, padding, ceil_mode, count_include_pad)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.Avg_pool1dBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._kernel_size = kernel_size
        grad_fn._stride = stride
        grad_fn._padding = padding
        grad_fn._ceil_mode = ceil_mode
        grad_fn._count_include_pad = count_include_pad
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def avg_pool2d_autograd(self, kernel_size, stride, padding=None, ceil_mode=False, count_include_pad=True, divisor_override=None):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("avg_pool2d", raw_keyset, self, kernel_size, stride, padding, ceil_mode, count_include_pad, divisor_override)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.Avg_pool2dBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._kernel_size = kernel_size
        grad_fn._stride = stride
        grad_fn._padding = padding
        grad_fn._ceil_mode = ceil_mode
        grad_fn._count_include_pad = count_include_pad
        grad_fn._divisor_override = divisor_override
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def avg_pool3d_autograd(self, kernel_size, stride, padding=None, ceil_mode=False, count_include_pad=True):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("avg_pool3d", raw_keyset, self, kernel_size, stride, padding, ceil_mode, count_include_pad)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.Avg_pool3dBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._kernel_size = kernel_size
        grad_fn._stride = stride
        grad_fn._padding = padding
        grad_fn._ceil_mode = ceil_mode
        grad_fn._count_include_pad = count_include_pad
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def adaptive_avg_pool1d_autograd(self, output_size):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("adaptive_avg_pool1d", raw_keyset, self, output_size)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.Adaptive_avg_pool1dBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._output_size = output_size
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def adaptive_avg_pool2d_autograd(self, output_size):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("adaptive_avg_pool2d", raw_keyset, self, output_size)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.Adaptive_avg_pool2dBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._output_size = output_size
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def adaptive_avg_pool3d_autograd(self, output_size):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("adaptive_avg_pool3d", raw_keyset, self, output_size)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.Adaptive_avg_pool3dBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._output_size = output_size
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def adaptive_max_pool1d_autograd(self, output_size, return_indices=False):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("adaptive_max_pool1d", raw_keyset, self, output_size, return_indices)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.Adaptive_max_pool1dBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self, result=result)
        grad_fn._output_size = output_size
        grad_fn._return_indices = return_indices
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def adaptive_max_pool2d_autograd(self, output_size, return_indices=False):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("adaptive_max_pool2d", raw_keyset, self, output_size, return_indices)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.Adaptive_max_pool2dBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self, result=result)
        grad_fn._output_size = output_size
        grad_fn._return_indices = return_indices
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def upsample_nearest1d_autograd(self, output_size):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("upsample_nearest1d", raw_keyset, self, output_size)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.Upsample_nearest1dBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._output_size = output_size
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def upsample_nearest2d_autograd(self, output_size):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("upsample_nearest2d", raw_keyset, self, output_size)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.Upsample_nearest2dBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._output_size = output_size
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def upsample_bilinear2d_autograd(self, output_size, align_corners=False, scales_h=None, scales_w=None):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("upsample_bilinear2d", raw_keyset, self, output_size, align_corners, scales_h, scales_w)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.Upsample_bilinear2dBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._output_size = output_size
        grad_fn._align_corners = align_corners
        grad_fn._scales_h = scales_h
        grad_fn._scales_w = scales_w
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def upsample_linear1d_autograd(self, output_size, align_corners=False, scales=None):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("upsample_linear1d", raw_keyset, self, output_size, align_corners, scales)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.Upsample_linear1dBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._output_size = output_size
        grad_fn._align_corners = align_corners
        grad_fn._scales = scales
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def upsample_bicubic2d_autograd(self, output_size, align_corners=False, scales_h=None, scales_w=None):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("upsample_bicubic2d", raw_keyset, self, output_size, align_corners, scales_h, scales_w)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.Upsample_bicubic2dBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._output_size = output_size
        grad_fn._align_corners = align_corners
        grad_fn._scales_h = scales_h
        grad_fn._scales_w = scales_w
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result
