"""Auto-generated forward autograd wrappers — DO NOT EDIT.

Generated by tools/autograd/gen_variable_type.py from derivatives.yaml.
"""
from __future__ import annotations

from ..autograd.grad_mode import GradMode
from ..autograd.anomaly_mode import annotate_node_creation
from .._backends.autograd import _strip_autograd_keys
from .._dispatch.dispatcher import current_dispatch_keyset, redispatch
from . import functions as _F



def exp_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("exp", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.ExpBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(result=result)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def log_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("log", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.LogBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def sqrt_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("sqrt", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.SqrtBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def rsqrt_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("rsqrt", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.RsqrtBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def neg_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("neg", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.NegBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def abs_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("abs", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.AbsBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def sigmoid_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("sigmoid", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.SigmoidBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def tanh_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("tanh", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.TanhBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def sin_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("sin", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.SinBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def cos_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("cos", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.CosBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def relu_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("relu", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.ReluBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def add_autograd(self, other):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("add", raw_keyset, self, other)
    if GradMode.enabled and (getattr(self, 'requires_grad', False) or getattr(other, 'requires_grad', False)):
        grad_fn = _F.AddBackward0((self, other,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self, other=other)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def mul_autograd(self, other):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("mul", raw_keyset, self, other)
    if GradMode.enabled and (getattr(self, 'requires_grad', False) or getattr(other, 'requires_grad', False)):
        grad_fn = _F.MulBackward0((self, other,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(other=other, self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def sub_autograd(self, other):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("sub", raw_keyset, self, other)
    if GradMode.enabled and (getattr(self, 'requires_grad', False) or getattr(other, 'requires_grad', False)):
        grad_fn = _F.SubBackward0((self, other,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self, other=other)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def div_autograd(self, other):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("div", raw_keyset, self, other)
    if GradMode.enabled and (getattr(self, 'requires_grad', False) or getattr(other, 'requires_grad', False)):
        grad_fn = _F.DivBackward0((self, other,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(other=other, self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def matmul_autograd(self, other):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("matmul", raw_keyset, self, other)
    if GradMode.enabled and (getattr(self, 'requires_grad', False) or getattr(other, 'requires_grad', False)):
        grad_fn = _F.MatmulBackward0((self, other,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(other=other, self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def reshape_autograd(self, shape):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("reshape", raw_keyset, self, shape)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.ReshapeBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._shape = shape
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def transpose_autograd(self, dim0, dim1):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("transpose", raw_keyset, self, dim0, dim1)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.TransposeBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._dim0 = dim0
        grad_fn._dim1 = dim1
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def permute_autograd(self, dims):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("permute", raw_keyset, self, dims)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.PermuteBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._dims = dims
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def expand_autograd(self, size):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("expand", raw_keyset, self, size)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.ExpandBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._size = size
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def squeeze_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("squeeze", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.SqueezeBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def unsqueeze_autograd(self, dim):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("unsqueeze", raw_keyset, self, dim)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.UnsqueezeBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._dim = dim
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def sum_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("sum", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.SumBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def mean_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("mean", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.MeanBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def contiguous_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("contiguous", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.ContiguousBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def erf_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("erf", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.ErfBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def softplus_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("softplus", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.SoftplusBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def silu_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("silu", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.SiluBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def gelu_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("gelu", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.GeluBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def mish_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("mish", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.MishBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def leaky_relu_autograd(self, negative_slope=0.01):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("leaky_relu", raw_keyset, self, negative_slope)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.Leaky_reluBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._negative_slope = negative_slope
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def elu_autograd(self, alpha=1.0):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("elu", raw_keyset, self, alpha)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.EluBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._alpha = alpha
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def celu_autograd(self, alpha=1.0):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("celu", raw_keyset, self, alpha)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.CeluBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._alpha = alpha
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def hardtanh_autograd(self, min_val=-1.0, max_val=1.0):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("hardtanh", raw_keyset, self, min_val, max_val)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.HardtanhBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._min_val = min_val
        grad_fn._max_val = max_val
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def relu6_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("relu6", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.Relu6Backward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def hardswish_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("hardswish", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.HardswishBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def hardsigmoid_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("hardsigmoid", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.HardsigmoidBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def selu_autograd(self):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("selu", raw_keyset, self)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.SeluBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def softmax_autograd(self, dim):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("softmax", raw_keyset, self, dim)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.SoftmaxBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._dim = dim
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def log_softmax_autograd(self, dim):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("log_softmax", raw_keyset, self, dim)
    if GradMode.enabled and (self.requires_grad):
        grad_fn = _F.Log_softmaxBackward0((self,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self)
        grad_fn._dim = dim
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def prelu_autograd(self, weight):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("prelu", raw_keyset, self, weight)
    if GradMode.enabled and (getattr(self, 'requires_grad', False) or getattr(weight, 'requires_grad', False)):
        grad_fn = _F.PreluBackward0((self, weight,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(self_=self, weight=weight)
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def layer_norm_autograd(input, normalized_shape, weight, bias, eps=1e-5):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("layer_norm", raw_keyset, input, normalized_shape, weight, bias, eps)
    if GradMode.enabled and (input.requires_grad):
        grad_fn = _F.Layer_normBackward0((input,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(input=input, weight=weight)
        grad_fn._normalized_shape = normalized_shape
        grad_fn._eps = eps
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def batch_norm_autograd(input, running_mean, running_var, weight, bias, training=False, momentum=0.1, eps=1e-5):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("batch_norm", raw_keyset, input, running_mean, running_var, weight, bias, training, momentum, eps)
    if GradMode.enabled and (input.requires_grad):
        grad_fn = _F.Batch_normBackward0((input,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(input=input, weight=weight)
        grad_fn._training = training
        grad_fn._momentum = momentum
        grad_fn._eps = eps
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def group_norm_autograd(input, num_groups, weight, bias, eps=1e-5):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("group_norm", raw_keyset, input, num_groups, weight, bias, eps)
    if GradMode.enabled and (input.requires_grad):
        grad_fn = _F.Group_normBackward0((input,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(input=input, weight=weight)
        grad_fn._num_groups = num_groups
        grad_fn._eps = eps
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result


def rms_norm_autograd(input, normalized_shape, weight, eps=1e-6):
    active_keyset = current_dispatch_keyset()
    raw_keyset = _strip_autograd_keys(active_keyset)
    result = redispatch("rms_norm", raw_keyset, input, normalized_shape, weight, eps)
    if GradMode.enabled and (input.requires_grad):
        grad_fn = _F.Rms_normBackward0((input,), raw_keyset=raw_keyset, active_keyset=active_keyset)
        annotate_node_creation(grad_fn)
        grad_fn._save(input=input, weight=weight)
        grad_fn._normalized_shape = normalized_shape
        grad_fn._eps = eps
        result.grad_fn = grad_fn
        result.requires_grad = True
    return result
